### PR TITLE
Wip/hughsie/guess format

### PR DESCRIPTION
**Pull request by hughsie**

### CODE REVIEW

**Comment by hughsie** [comment]
@superm1 if this works for you I think we should push out a release ASAP.

**Comment by superm1** [comment]
I gave a try with it, and unfortunately same failure when called with `fwupdmgr install FILE.cab`

```
14:22:54:0465 FuMain               Called Install(*,7)
14:22:54:0465 FuMain               got option reason
14:22:54:0465 FuMain               got option filename
14:22:54:0473 FuEngine             Emitting PropertyChanged('Status'='decompressing')
14:22:54:0473 FuMain               Emitting PropertyChanged('Status'='decompressing')
14:22:54:0496 FuCommonCab          processing folder: 1/1
14:22:54:0496 FuCommonCab          processing file: firmware.metainfo.xml
14:22:54:0496 FuCommonCab          processing file: firmware.bin
14:22:54:0497 FuCommonCab          processing file: catalog.cat
14:22:54:0497 FuCommonCab          processing file: firmware.inf
14:22:54:0497 FuCommonCab          processing file: README.txt
14:22:54:0497 FuCommonCab          processing file: firmware.bin.asc
14:22:54:0527 XbSilo               compiling db24bf6b315bf461913b8d1f6e7ff39416138877:prefix=components…
14:22:54:0527 XbSilo               0.03ms      compile db24bf6b315bf461913b8d1f6e7ff39416138877:prefix=components
14:22:54:0527 FuCommonCab          invalid container checksum (null), fixing up to bc54b981a88a2cd85678b46cf6edc471dfb13000
14:22:54:0527 XbSilo               0.09ms      get size nodetab
14:22:54:0527 XbSilo               0.01ms      adding strtab element
14:22:54:0527 XbSilo               0.00ms      adding strtab attr name
14:22:54:0527 XbSilo               0.00ms      adding strtab attr value
14:22:54:0527 XbSilo               0.01ms      adding strtab text
14:22:54:0527 XbSilo               0.00ms      writing nodetab
14:22:54:0527 XbSilo               0.00ms      fixing ->parent and ->next
14:22:54:0527 XbSilo               0.00ms      appending strtab
14:22:54:0527 XbSilo               0.00ms      parse blob
14:22:54:0527 XbSilo               0.01ms      query on / with `components/component` limit=0 -> 1 results
14:22:54:0527 XbSilo               0.00ms      query on component with `releases/release` limit=0 -> 1 results
14:22:54:0527 FuCommonCab          processing release: 0x10201
14:22:54:0527 XbSilo               0.01ms      query on release with `checksum[@target='content']` limit=1 -> 0 results
14:22:54:0527 FuEngine             Emitting PropertyChanged('Status'='idle')
14:22:54:0527 FuMain               Emitting PropertyChanged('Status'='idle')
14:22:54:0527 XbSilo               0.00ms      query on / with `components/component` limit=0 -> 1 results
14:22:54:0527 XbSilo               0.01ms      query on component with `provides/firmware[@type='flashed']` limit=0 -> 1 results
14:22:54:0527 XbSilo               0.00ms      query on component with `id` limit=1 -> 1 results
14:22:54:0527 FuMain               requirement on d48d4e219eaa1c98a7d7081b3ba101676351a581:com.dell.uefice945437.firmware failed: No supported devices found
14:22:54:0527 XbSilo               0.01ms      query on component with `provides/firmware[@type='flashed']` limit=0 -> 1 results
14:22:54:0527 XbSilo               0.00ms      query on component with `id` limit=1 -> 1 results
14:22:54:0527 FuMain               requirement on 18b60de14e31ac83cc59156460caaff477d86d5f:com.dell.uefice945437.firmware failed: No supported devices found
14:22:54:0527 XbSilo               0.01ms      query on component with `provides/firmware[@type='flashed']` limit=0 -> 1 results
14:22:54:0527 XbSilo               0.00ms      query on component with `id` limit=1 -> 1 results
14:22:54:0527 FuMain               requirement on acb404019656654d44f80922d94735e831d9bb40:com.dell.uefice945437.firmware failed: No supported devices found
14:22:54:0527 XbSilo               0.01ms      query on component with `provides/firmware[@type='flashed']` limit=0 -> 1 results
14:22:54:0527 XbSilo               0.00ms      query on component with `id` limit=1 -> 1 results
14:22:54:0527 FuMain               requirement on a455a3a21752e5d31c228f1f5b51761dad88a432:com.dell.uefice945437.firmware failed: No supported devices found
14:22:54:0527 XbSilo               0.01ms      query on component with `provides/firmware[@type='flashed']` limit=0 -> 1 results
14:22:54:0527 XbSilo               0.00ms      query on component with `id` limit=1 -> 1 results
14:22:54:0527 FuMain               requirement on 1eca9eabb0c992c136e1deb1f89e3f70c465aa1c:com.dell.uefice945437.firmware failed: No supported devices found
14:22:54:0527 XbSilo               0.01ms      query on component with `provides/firmware[@type='flashed']` limit=0 -> 1 results
14:22:54:0527 XbSilo               0.00ms      query on component with `id` limit=1 -> 1 results
14:22:54:0527 FuMain               requirement on 58931e8c9ef5eead9c007563814f96fcadb1b993:com.dell.uefice945437.firmware failed: No supported devices found
14:22:54:0527 XbSilo               0.01ms      query on component with `provides/firmware[@type='flashed']` limit=0 -> 1 results
14:22:54:0527 XbSilo               0.00ms      query on component with `id` limit=1 -> 1 results
14:22:54:0527 FuMain               requirement on ca36279eeac13463fd5d974c88794859294fbfb1:com.dell.uefice945437.firmware failed: No supported devices found
14:22:54:0527 XbSilo               0.01ms      query on component with `provides/firmware[@type='flashed']` limit=0 -> 1 results
14:22:54:0527 XbSilo               0.00ms      query on component with `releases/release` limit=1 -> 1 results
14:22:54:0527 XbSilo               0.00ms      query on component with `id` limit=1 -> 1 results
14:22:54:0527 FuMain               requirement on 6c24a747f97668873b761558e322398a91dbf394:com.dell.uefice945437.firmware failed: Firmware version formats were different, device was 'quad' and release is 'plain'
14:22:54:0527 XbSilo               0.01ms      query on component with `provides/firmware[@type='flashed']` limit=0 -> 1 results
14:22:54:0527 XbSilo               0.00ms      query on component with `id` limit=1 -> 1 results
14:22:54:0527 FuMain               requirement on 2e59657d5e0beb043a16639968ca6178bcedff42:com.dell.uefice945437.firmware failed: No supported devices found
14:22:54:0528 XbSilo               0.01ms      query on component with `provides/firmware[@type='flashed']` limit=0 -> 1 results
14:22:54:0528 XbSilo               0.00ms      query on component with `id` limit=1 -> 1 results
14:22:54:0528 FuMain               requirement on bbbf1ce3d1cf15550c3760b354592040292415bb:com.dell.uefice945437.firmware failed: No supported devices found
14:22:54:0528 XbSilo               0.01ms      query on component with `provides/firmware[@type='flashed']` limit=0 -> 1 results
14:22:54:0528 XbSilo               0.00ms      query on component with `id` limit=1 -> 1 results
14:22:54:0528 FuMain               requirement on f954c7acdf5fab61aeaca1cd71d29ea5ade6992f:com.dell.uefice945437.firmware failed: No supported devices found
```

**Comment by hughsie** [comment]
Can you share the .cab file you used? Did it have exactly `<developer_name>Dell Inc.</developer_name>`? I don't see any of the new `using VersionFormat...` output.

**Comment by superm1** [comment]
It was from `3d49e33f0c819e2c1c7ac27cd6dd025e27abe787-Signed_1152921504627938788.cab` which came from LVFS.

This was the XML contained in it:
```
<component type="firmware">
  <id>com.dell.uefice945437.firmware</id>
  <provides>
    <firmware type="flashed">ce945437-7358-49f1-95d8-6b694a10a755</firmware>
  </provides>
  <name>XPS 13 9380 System Update</name>
  <summary>Firmware for the Dell XPS 13 9380</summary>
  <description>
    <p>
      Updating the system firmware improves performance.
    </p>
  </description>
  <url type="homepage">http://support.dell.com/</url>
  <metadata_license>CC0-1.0</metadata_license>
  <project_license>proprietary</project_license>
  <developer_name>Dell Inc.</developer_name>
  <releases>
    <release version="0x10201" timestamp="1550139907">
    </release>
  </releases>
</component>
```

**Comment by hughsie** [comment]
@superm1 can you try with those two extra commits? I think it should work now.

**Comment by superm1** [comment]
Yep, that looks good now.

**Pull request merged**
