### PR TITLE
Workaround kernel and userspace race for thunderbolt nvm_version read 

### PR DESCRIPTION
**Pull request by superm1**

### CODE REVIEW

**Comment by superm1** [comment]
+@YehezkelShB and @finikorg for awareness and review.

**Comment by superm1** [comment]
+@westeri for awareness too.  @westeri there have been various reports of "00.00" NVM version that I originally thought were caused by thunderbolt-power race condition we have the other PR for, but I think this is actually a kernel -> userspace race condition trying to read `nvm_version` within a second of the uevent coming through.

I've seen the reports across LVFS upgrade reports, stuff at dell/thunderbolt-nvm-linux and Launchpad.

**Comment by westeri** [comment]
The nvm_version returns -EAGAIN if the NVM is not yet ready to be read (since it takes some time to get the Linux NVMem devices up and running). Maybe you can use that information and retry when you get -EAGAIN when reading nvm_version?

**Comment by gicmo** [comment]
@YehezkelShB `g_udev_device_get_sysfs_attr` is a tiny wrappre around `udev_device_get_sysattr_value` (see [gudevdevice.c#L780](https://gitlab.gnome.org/GNOME/libgudev/blob/master/gudev/gudevdevice.c#L780)), which I believe does indeed set `errno` (IIRC I am using that fact in bolt, where I am using libudev directly).

**Comment by superm1** [comment]
Thanks for the feedback guys.  I've adjusted it to instead look specifically for `EAGAIN` and retry on that criteria.

**Comment by superm1** [comment]
In the downstream launchpad bug a tester did confirm that this PR works for them.  You can confirm in their log (with debug turned on) that the kernel responded `-EAGAIN` and the plugin retried.
https://bugs.launchpad.net/ubuntu/+source/fwupd/+bug/1768627/+attachment/5169606/+files/fwupd_journal2.txt

**Comment by frigi83** [comment]
I have tested this on my Dell XPS and it work's. I don't have any more the message of a wrong version. [Launchpad bug](https://bugs.launchpad.net/ubuntu/+source/fwupd/+bug/1768627)

**Pull request merged**
