### PR TITLE
Update the UEFI UX Capsule Header checksum when needed.

### PR DESCRIPTION
**Pull request by vathpela**
Signed-off-by: Peter Jones <pjones@redhat.com>

Type of pull request:
- [ ] New plugin (Please include [new plugin checklist](https://github.com/hughsie/fwupd/wiki/New-plugin-checklist))
- [x] Code fix
- [ ] Feature
- [ ] Documentation

### CODE REVIEW

**Comment by superm1** [comment]
When does this situation actually happen?  Isn't it supposed to be calculated in OS (where it's actually multithreaded)? https://github.com/hughsie/fwupd/blob/master/plugins/uefi/fu-plugin-uefi.c#L227

**Comment by vathpela** [comment]
Any time the vendor uses a mode other than 0, fwup_get_gop_mode() is going to render that header invalid.  (Not sure how threading would matter; it's one cacheline and only a few instructions.)

**Comment by superm1** [comment]
> Any time the vendor uses a mode other than 0, fwup_get_gop_mode() is going to render that header invalid

Why would the gop mode be different in UEFI and in OS though?

>Not sure how threading would matter; it's one cacheline and only a few instructions

I recall back with fwupdate that there was a performance problem with doing checksums in UEFI.  It was more because of drawing status to the screen while doing the checksum though.

**Comment by vathpela** [comment]
> > Any time the vendor uses a mode other than 0, fwup_get_gop_mode() is going to render that header invalid
> 
> Why would the gop mode be different in UEFI and in OS though?

It usually won't be, but there's no guarantee of that, and *also* we currently don't have the GOP mode exposed anywhere in the OS, so we're just defaulting to always having 0 there currently.  I've posted a kernel patch to expose it so we could set this all up on the userland side, but for now we need to do this here.

> > Not sure how threading would matter; it's one cacheline and only a few instructions
> 
> I recall back with fwupdate that there was a performance problem with doing checksums in UEFI. It was more because of drawing status to the screen while doing the checksum though.

Yeah, that's just because GOP isn't all that good to begin with, and often the framebuffer memory is mapped as write-through without the write-combining attribute.

**Pull request merged**
