### PR TITLE
Add TB18DC to the synapticmst plugin list

### PR DESCRIPTION
**Pull request by martonmiklos**
Hi fwupd developers,

First of all many thanks for your all efforts and work put into this project!

This PR adds the Dell TB18DC docking station to the readme of the synapticsmst plugin which might be helpful to others in the future. 

I have a Dell Precision 7530 with a TB18DC dock. Upgrading the Synaptics MST chips failed with the official tools on Windows, but the fwupd lists them properly so it turned out that they have the latest (3.12.0.2) firmware so all of my unsuccessful efforts of the upgrade was pointless on Windows.

### CODE REVIEW

**Comment by hughsie** [comment]
@superm1?

**Comment by superm1** [comment]
I haven't actually tested TB18DC with fwupd, but it is supposed to be the same as TB16 from an MST perspective.

Can you please confirm the fwupdmgr get-devices output for it?

**Comment by superm1** [comment]
Here is the output from a TB16.

```
Synaptics VMM3330 inside Dell WD15/TB16/TB18 wired Dock
  DeviceId:             7b3cbc344094ace839263dd4711c84ea99bb6dc3
  Guid:                 c0f73159-4fc0-509b-80f8-5f871f3751a8
  Guid:                 be025b25-ca5c-546c-97c6-ee2160ba489d
  Guid:                 190e8d7c-6bcf-5fab-94e7-4f8739eb90aa
  Summary:              Multi-Stream Transport Device
  Plugin:               synapticsmst
  Flags:                updatable|supported|registered
  Vendor:               Synaptics
  Version:              3.12.002
  Icon:                 computer
  Created:              2018-12-17

Synaptics VMM3320 inside Dell WD15/TB16/TB18 wired Dock
  DeviceId:             d83854e8c81f5d47b0b99c8a3b42ae5127c75eb8
  Guid:                 152a9833-41e6-5c21-9dde-0ff8984f3e20
  Guid:                 0a52c8c7-26d5-59a0-ae44-6b00e276d775
  Guid:                 51000744-2de6-5a52-8a86-d5f69fd73d34
  Summary:              Multi-Stream Transport Device
  Plugin:               synapticsmst
  Flags:                updatable|supported|registered
  Vendor:               Synaptics
  Version:              3.12.002
  Icon:                 computer
  Created:              2018-12-17
```

In terms of how the GUIDs are constructed the TB18 does get a GUID built, that last one should correspond to working on a TB18.

```
[SynapticsMSTBoardID=274]
Name = Dell WD15/TB16/TB18 wired Dock
DeviceKind = wd15,tb16,tb18
```

So yes, this change looks correct.

**Comment by superm1** [comment]
Can you please squash them to one commit though?

**Comment by martonmiklos** [comment]
Squashed, I can test it on Thursday closest, I will report back with a log.

**Comment by martonmiklos** [comment]
Here is the  fwupdmgr get-devices:

`mm@mm-precision:~$ sudo fwupdmgr get-devices
Precision 7530 Thunderbolt Controller
  DeviceId:             40fa16b4985de8222e1110d9075a43c061bb18ba
  Guid:                 c50677e2-fbcb-5f7a-b109-cd3de11a6401
  Summary:              Unmatched performance for high-speed I/O
  Plugin:               thunderbolt
  Flags:                internal|updatable|supported|registered
  Vendor:               Dell
  VendorId:             TBT:0x00D4
  Version:              36.00
  Icon:                 computer
  Created:              2018-12-20

Dell Thunderbolt Cable
  DeviceId:             994fdecf82a2618c579e68b9156078c3bbdfdfd3
  Guid:                 b4fd3cdf-4e3a-5090-a583-45367cfd6421
  Plugin:               thunderbolt
  Flags:                updatable|registered
  Vendor:               Dell
  VendorId:             TBT:0x00D4
  Version:              26.06
  Icon:                 audio-card
  Created:              2018-12-20

Dell Thunderbolt Dock
  DeviceId:             df470c62a0205df8debd2a188a06f22746b77258
  Guid:                 76cc74d4-f062-5b93-a11c-8d2a58a25848                                                                                                                                                                                                                                                                                                              
  Plugin:               thunderbolt                                                                                                                                                                                                                                                                                                                                       
  Flags:                updatable|registered                                                                                                                                                                                                                                                                                                                              
  Vendor:               Dell                                                                                                                                                                                                                                                                                                                                              
  VendorId:             TBT:0x00D4                                                                                                                                                                                                                                                                                                                                        
  Version:              27.00                                                                                                                                                                                                                                                                                                                                             
  Icon:                 audio-card                                                                                                                                                                                                                                                                                                                                        
  Created:              2018-12-20                                                                                                                                                                                                                                                                                                                                        
                                                                                                                                                                                                                                                                                                                                                                          
Synaptics VMM3320 inside Dell WD15/TB16 wired Dock                                                                                                                                                                                                                                                                                                                        
  DeviceId:             7b3cbc344094ace839263dd4711c84ea99bb6dc3                                                                                                                                                                                                                                                                                                          
  Guid:                 152a9833-41e6-5c21-9dde-0ff8984f3e20                                                                                                                                                                                                                                                                                                              
  Guid:                 0a52c8c7-26d5-59a0-ae44-6b00e276d775                                                                                                                                                                                                                                                                                                              
  Guid:                 51000744-2de6-5a52-8a86-d5f69fd73d34                                                                                                                                                                                                                                                                                                              
  Summary:              Multi-Stream Transport Device                                                                                                                                                                                                                                                                                                                     
  Plugin:               synapticsmst                                                                                                                                                                                                                                                                                                                                      
  Flags:                updatable|registered                                                                                                                                                                                                                                                                                                                              
  Vendor:               Synaptics                                                                                                                                                                                                                                                                                                                                         
  Version:              3.12.002                                                                                                                                                                                                                                                                                                                                          
  Icon:                 computer                                                                                                                                                                                                                                                                                                                                          
  Created:              2018-12-20                                                                                                                                                                                                                                                                                                                                        
                                                                                                                                                                                                                                                                                                                                                                          
Synaptics VMM3330 inside Dell WD15/TB16 wired Dock                                                                                                                                                                                                                                                                                                                        
  DeviceId:             d83854e8c81f5d47b0b99c8a3b42ae5127c75eb8                                                                                                                                                                                                                                                                                                          
  Guid:                 c0f73159-4fc0-509b-80f8-5f871f3751a8                                                                                                                                                                                                                                                                                                              
  Guid:                 be025b25-ca5c-546c-97c6-ee2160ba489d                                                                                                                                                                                                                                                                                                              
  Guid:                 190e8d7c-6bcf-5fab-94e7-4f8739eb90aa                                                                                                                                                                                                                                                                                                              
  Summary:              Multi-Stream Transport Device                                                                                                                                                                                                                                                                                                                     
  Plugin:               synapticsmst                                                                                                                                                                                                                                                                                                                                      
  Flags:                updatable|registered                                                                                                                                                                                                                                                                                                                              
  Vendor:               Synaptics                                                                                                                                                                                                                                                                                                                                         
  Version:              3.12.002                                                                                                                                                                                                                                                                                                                                          
  Icon:                 computer                                                                                                                                                                                                                                                                                                                                          
  Created:              2018-12-20                                                                                                                                                                                                                                                                                                                                        
                                                                                                                                                                                                                                                                                                                                                                          
Precision 7530 System Firmware                                                                                                                                                                                                                                                                                                                                            
  DeviceId:             f6d8adf7724cb115dbb7e99b52f70ddbe1168be0                                                                                                                                                                                                                                                                                                          
  Guid:                 db72c932-b3c6-4640-b382-3f4619ab447b                                                                                                                                                                                                                                                                                                              
  Guid:                 230c8b18-8d9b-53ec-838b-6cfc0383493a                                                                                                                                                                                                                                                                                                              
  Plugin:               uefi                                                                                                                                                                                                                                                                                                                                              
  Flags:                internal|updatable|require-ac|supported|registered|needs-reboot                                                                                                                                                                                                                                                                                   
  Version:              0.1.5.2                                                                                                                                                                                                                                                                                                                                           
  VersionLowest:        0.1.5.2                                                                                                                                                                                                                                                                                                                                           
  Icon:                 computer                                                                                                                                                                                                                                                                                                                                          
  Created:              2018-12-20        `

**Pull request merged**
