### PR TITLE
Create a silo index to speed up GUID queries

### PR DESCRIPTION
**Pull request by hughsie**
This speeds up matching for GUIDs by about 90%, taking the query from 3.17ms to
about 0.33ms on my Thinkpad. This is more important for slow ARM hardware,
where strcmp() is more expensive than on x64.

### CODE REVIEW

**Comment by superm1** [comment]
I guess you'll need to get libxmlb 0.1.4 out the door first for this to pass CI.

**Comment by superm1** [comment]
Need to bump `subprojects/libxmlb.wrap` too.

**Comment by hughsie** [comment]
We won't actually need libstemmer -- it might be better to just disable it in the subproject build. Up to you whether you think we should build it or not. I don't think fwupd needs to do free-text searches anywhere, but I suppose it could in the future -- e.g. `fwupdmgr search foo`

There is a test failure that's actually my fault; let me handle my dodgy patch.

**Comment by superm1** [comment]
In that case yeah drop the patch when you fix up your test failure and turn off stemmer support in the subproject build.

**Comment by superm1** [comment]
If we have support for fwupd search in the future then yeah lets make it mandatory then.  It will mean that we have to make sure there is actually a test that it was compiled with the right flags too that means.

**Comment by hughsie** [comment]
> In that case yeah drop the patch

Will do. I'm thinking of turning off the stemming support by default in libxmlb -- which I think will also fix these problems too. It means waiting for 0.1.5 but we probably need that for https://github.com/hughsie/libxmlb/commit/5e69eb7424f24b007add52a0fb0eddf26628d215 unless we ifdef things.

> It will mean that we have to make sure there is actually a test that it was compiled with the right flags

If libxmlb doesn't get libstemmer it does a semi-sane fallback.

Richard.

**Comment by superm1** [comment]
>  It means waiting for 0.1.5

yeah I guess so

**Pull request merged**
