### PR TITLE
Correctly parse DFU interfaces with extra vendor-specific data

### PR DESCRIPTION
**Pull request by hughsie**
Fixes: https://github.com/hughsie/fwupd/issues/1152

### CODE REVIEW

**Comment by superm1** [comment]
This should still fail because of:
`if (desc.bLength != sz) {` below (`sz` will be bigger than `desc.bLength`)

**Comment by hughsie** [comment]
> This should still fail

Are you sure? Surely `bLength` should always be the same size as the length of the functional descriptor, even with extra vendor-specific data included...

**Comment by superm1** [comment]
Yeah one of my colleagues just double checked that it fails this other check.

I looked at https://www.usb.org/sites/default/files/DFU_1.1.pdf again and it does prescribe that it should be 0x09, and if you look at the USB descriptor dumps in #1152 it's 0x09 for both USB interface descriptor and device firmware upgrade descriptor.

**Comment by hughsie** [comment]
Okay, many thanks for testing. Does ^^ work?

**Pull request merged**
