### PR TITLE
l10n: Added Lithuanian translation

### PR DESCRIPTION
**Pull request by welaq**
Type of pull request:
- [ ] New plugin (Please include [new plugin checklist](https://github.com/hughsie/fwupd/wiki/New-plugin-checklist))
- [ ] Code fix
- [X] Feature
- [ ] Documentation

### CODE REVIEW

**Comment by hughsie** [comment]
Could you submit this to https://www.transifex.com/ please? Otherwise it's going to get overwritten when we sync the release translations. Thanks.

**Comment by welaq** [comment]
Actually the organization on Transifex is probably dead because nobody is accepting requests to add new languages or join teams. Year ago I sent request to join a team still didn't get no answer.

**Comment by hughsie** [comment]
There's already an `'lt` team, have you tried emailing `mantas@akl.lt` directly?

**Comment by hughsie** [comment]
I've pushed these to tx myself, thanks.

**Comment by welaq** [comment]
Thank you for pushing! I'll try to contact him to see if I can get any answer.

**Pull request merged**
