### PR TITLE
uefi: Port the TPM unlocking functionality from Dell plugin (Fixes: #775)

### PR DESCRIPTION
**Pull request by superm1**
This requires some testing, I don't have the right HW handy at the moment, but the reporter hopefully can check.

### CODE REVIEW

**Comment by hughsie** [comment]
Maybe I'm missing something, but why does it fix the bug?

**Comment by superm1** [comment]
Well I don't know for sure it does yet :)

But the reason I think it should is because the device was registered through uefi and the registered proxy notification.  So the unlock method that's being called should be called from UEFI plugin not Dell plugin now.

**Comment by superm1** [comment]
From the testing done on #775 I'd say this part of the change is correct (the unlock routine now works).

**Comment by hughsie** [comment]
I don't think the dell stuff needs to leak into the uefi plugin; is the actual bug that the unlock method is called on the "wrong" plugin?

**Comment by superm1** [comment]
Well 2 bugs here really.
1. Esp path isn't set on the proxy registered devices. This is fixed by plugin ordering so that coldplug for uefi runs first.
2. Unlock method expected for the device doesn't match the plugin "owning" the device. So yes it's as though you want the "original" plugin's unlock method to be called.

**Comment by superm1** [comment]
The OP in the original issue did confirm that these two patches fixed the problem for them and they could switch modes.

**Pull request merged**
