### PR TITLE
Generate debian/control dynamically

### PR DESCRIPTION
**Pull request by superm1**
Hardcoding the same thing in two places is silly, so let this get dynamically generated.

### CODE REVIEW

**Comment by superm1** [comment]
Any more thoughts on this?  I should probably fix the conflict and merge before you do anything to dependencies.txt for #295

**Comment by hughsie** [comment]
I've been thinking about this. I really do think we've outgrown the CSV mega-table -- we want to add runtime deps, and versions for deps, and I'm really thinking we want something more "full fat" like a proper XML document. Also, something that's more immune to merge conflicts between branches. We're reading from a python program so it's really no sweat reading XML rather than a CSV. I haven't thought much about the schema, but it could either be top-down or bottom-up, e.g. 

    <dep distro="debian" type="build">appstream-glib-dev</dep>
    <dep distro="fedora" type="build">appstream-glib</dep>
    <dep distro="debian" type="build">json1-dev</dep>
    <dep distro="fedora" type="build">json</dep>

or

    <distro id="fedora">
      <build>appstream-glib</build>
      <runtime>bubblewrap</runtime>
    </distro>
    <distro id="debian">
      <build>appstream-glib-dev</build>
      <runtime>bubblewrap</runtime>
    </distro>

or even:

    <dep type="build" id="appstream-glib">
      <distro id="fedora">appstream-glib</distro>
      <distro id="debian">appstream-glib-dev</distro>
    </build>
    <dep type="runtime" id="bubblewrap">
      <distro id="fedora">bubblewrap</distro> <!-- maybe just use id for the <dep> if it's the same?
      <distro id="debian">bubblewrap</distro>
    </build>

**Comment by superm1** [comment]
Yeah XML will be way more readable, you're right.   I'll work on this.

**Comment by superm1** [comment]
Alright, that all look good (other than the lack of squashing)?

**Comment by hughsie** [comment]
Couple of typos, then squash down and LGTM. Thanks!

**Pull request merged**
