### PR TITLE
Add shared functionality for reading and writing with O_NONBLOCK

### PR DESCRIPTION
**Pull request by hughsie**
Two plugins have very similar code already, and we're about to get another.

Note: I'm not completely happy with the name... `FuTtyFlags` doesn't exactly roll off the tongue.

### CODE REVIEW

**Comment by superm1** [comment]
`FuTeleprinter` maybe?

**Comment by hughsie** [comment]
Maybe this should be a `FuCommonIO` GObject, abstracting the `fd` completely. I guess that makes it very close to a `GIOChannel` albeit with the all important timeout. The more I think about it, the more `FuChannel` or `FuIOChannel` make sense.

**Comment by superm1** [comment]
That sounds good to me.

**Comment by hughsie** [comment]
Okay, I'm basically happy with the new approach.

**Comment by hughsie** [comment]
> why not wrap timeout stuff around GIOChannel instead

A good question. GIOChannel was designed about a decade ago (!) well before gio. GIOChannel isn't actually a GObject. GIOChannel has a nasty habit of returning GIOStatus, so every method using it has to handle things like `EAGAIN` -- when I really want all the tricky unix fd stuff in one place so that the caller can just do `fu_io_channel_read_bytes()` and not care that the reads were done in 64 byte blocks, each needing retrying more than once.

I guess you could wrap FuIOChannel around GIOChannel, but I'm not sure what that would add -- it means rather than using g_poll() and blocking the current main loop we'd have to use something like `g_io_create_watch()` and set up a GMainLoop with a timer for the timeout. I could investigate that if you think it's going to be simpler, although it would have to be object-in-object rather than a derived type.

**Pull request merged**
