### PR TITLE
Add Native Language Support option to meson build file

### PR DESCRIPTION
**Pull request by djcampello**
New meson option to enable/disable Native Language Support.
See https://packages.gentoo.org/useflags/nls for motivation.

Change-Id: Ic48fd010240cdf5a78a9c7df4368e397e4dcf32a

Type of pull request:
- [ ] New plugin (Please include [new plugin checklist](https://github.com/hughsie/fwupd/wiki/New-plugin-checklist))
- [ ] Code fix
- [X ] Feature
- [ ] Documentation

### CODE REVIEW

**Comment by superm1** [comment]
So this won't entirely turn off translations everywhere.  There are still translations done for `data/remotes.d/*.xml`, `policy/*` and pulling the data from the `po/` directory for both of thoses.

**Comment by superm1** [comment]
The other question I would have is many source files `#include <glib/gi18n.h>` for translation support.  So they'll have translatability turned on, but just wouldn't find strings from this.  Is that expected behavior?

**Comment by djcampello** [comment]
> glib/gi18n.h



> The other question I would have is many source files `#include <glib/gi18n.h>` for translation support. So they'll have translatability turned on, but just wouldn't find strings from this. Is that expected behavior?

That's my understanding

**Comment by hughsie** [comment]
Why? What's the point?

**Comment by djcampello** [comment]
Chrome OS does not make use of localization since the tools are not accessible to the user. This files take space form our image so we really want to avoid installing them altogether. Alternative approaches have been considered but it seems that respecting nls USE flag is the preferred. See https://chromium-review.googlesource.com/c/chromiumos/overlays/chromiumos-overlay/+/1460451 for context.

**Comment by hughsie** [comment]
So if we want to save space, Mario is right we need to not merge various data files. My gut feeling this should live lower down in meson as a native option, rather than hacked in. Of course, the other option is that chromeos just deletes all the .po files before building...

**Comment by djcampello** [comment]
Updated the patch to install the missing files when disabling NLS.
Regarding meson native option: https://github.com/mesonbuild/meson/issues/821 has been proposed but have not seen anything going in on that front.

**Comment by hughsie** [comment]
Does the LINGUAS file idea work? That would be a much simpler solution...

**Comment by djcampello** [comment]
Adding this to the ebuild file on the src_prepare() step works. Will try to get this in...

+       if ! use nls ; then
+               echo > po/LINGUAS || die
+       fi

**Comment by superm1** [comment]
OK.  I guess we'll close this for now.  If that's rejected and we need to revisit here, go ahead and re-open.

**Pull request closed without merging**
