### PR TITLE
Add issue template

### PR DESCRIPTION
**Pull request by FredDeschenes**
As requested by @superm1 in #255 I've created an issue template. I went that way instead of a wiki page because everyone has to see it when they enter an issue, but they can still decide to not use it if they're entering something other than an actual issue (ex: improvement, question, etc). It's just markdown anyway so it could be switched to a wiki page easily.

You can see what it looks like for users by trying to enter a new issue in my fork [here](https://github.com/FredDeschenes/fwupd/issues/new).

### CODE REVIEW

**Comment by superm1** [comment]
Thanks! Yes this is better than a wiki.

The questions that are UEFI related can you indicate that they're only required for problems with UEFI plugin? (Eg efibootmgr, secure boot, tree/boot)

**Comment by hughsie** [comment]
LGTM.

**Comment by FredDeschenes** [comment]
@superm1 : Yup I'll update that

**Comment by superm1** [comment]
s/bootloader/plugin
And it lgtm

**Comment by superm1** [comment]
Thanks again!

**Pull request merged**
