### PR TITLE
Add plugin icons and support for looking those up

### PR DESCRIPTION
**Pull request by superm1**
This adds icons for some of the more popular plugins and infrastructure that a frontend could query to determine what icon to show for a plugin.

Type of pull request:
- [ ] New plugin (Please include [new plugin checklist](https://github.com/hughsie/fwupd/wiki/New-plugin-checklist))
- [ ] Code fix
- [x] Feature
- [ ] Documentation

### CODE REVIEW

**Comment by hughsie** [comment]
I think it would be much easier if the plugins all just installed a /usr/share/fwupd/icons/plugins/PLUGIN.png and we just symlinked e.g. dell-dock.png to dell.png? I'm not sure why we have to expose this on the device object. I also think the icons need to be all square, and probably also of a known size, e.g 128x128. Passing around absolute paths sounds like a headache for flatpak apps too.

**Comment by superm1** [comment]
> I think it would be much easier if the plugins all just installed a /usr/share/fwupd/icons/plugins/PLUGIN.png and we just symlinked e.g. dell-dock.png to dell.png?

> Passing around absolute paths sounds like a headache for flatpak apps too.

The problem I was mostly worried about is fwupd is installed in a different prefix than a frontend, the frontend will have no idea where to actually get the icons from.

Think of the scenario that someone is using a snapped fwupd and a snapped GFU, or a distro fwupd and a flatpak'ed GFU.  I was hoping to have those work properly.

> I'm not sure why we have to expose this on the device object

My thought was that in GFU when you click a device you see all the stuff about that device.  This logo would replace the "Plugin: $plugin", as an attribute of that device.

**Comment by superm1** [comment]
>  I also think the icons need to be all square, and probably also of a known size, e.g 128x128.

OK, I guess once we're aligned on the other concepts I'll figure out a way to rework them.

**Comment by hughsie** [comment]
> or a distro fwupd and a flatpak'ed GFU. I was hoping to have those work properly.

I think the only way to cross this kind of prefix difference is to send the icon as a blob or over an fd. As a 128x128 png it's going to be less than 64kb so maybe that's the way to do it? It does smell a bit like a hack. Maybe we should use the LVFS CDN afterall.

I guess another question is logically whether a logo is per-device, per-plugin, per-vendor or per-protocol. In GFU what would the logo convey to the user? I'm not sure it's hugely compelling for all the extra code.

**Comment by superm1** [comment]
>I guess another question is logically whether a logo is per-device, per-plugin, per-vendor or per-protocol. 

The way this is done right now it's per-plugin, but I actually think per-vendor conveys more information.  You could hypothetically put a big graphic in the top left corner when you click a device.  In that sense maybe _all_ of this code and graphics should just be part of GFU?

> In GFU what would the logo convey to the user? I'm not sure it's hugely compelling for all the extra code.

Well right now, I think the information that is in GFU for "Plugin" is entirely un-useful.
You know really in my opinion it's not super useful in `fwupdgmr` either; it's an artifact of the internals of fwupd that most people don't need to know about.

So maybe the right solution is to just hide that in the to_string() in fwupd and then to not show it in GFU either?

**Pull request closed without merging**
