### PR TITLE
fu-tool: Add a new flag that will log devices to a text file before an action

### PR DESCRIPTION
**Pull request by superm1**
The intended use case is for ChromeOS to be able to save information about
devices on the system when `fwupdtool update` was run to display in the UX at
a later time.

This hasn't been reviewed by Google yet, wanted to align it makes sense upstream first.

Type of pull request:
- [ ] New plugin (Please include [new plugin checklist](https://github.com/hughsie/fwupd/wiki/New-plugin-checklist))
- [ ] Code fix
- [x] Feature
- [ ] Documentation

### CODE REVIEW

**Comment by hughsie** [comment]
Back a bit; is this just saving the current state to a log file? I don't think we want to be parsing `fwupd_device_to_string()` from other programs. Could we do something like this instead?

    fwupdtool get-devices --output-format=json > log.json

If the log has to be created during the update, I think this makes sense too:

    fwupdtool update --output-format=json > log.json

**Comment by superm1** [comment]
The reason to combine it into the `update` call is to avoid firing off `fwupdtool` multiple times every time a udev supported device is plugged in.
The idea I have right now is that this is shown in `chrome://system` which doesn't do any parsing of the logs, it just shows some raw text output from various utilities.  The most interesting thing is device and version, so maybe instead this would be preferable to log:

```
Device: %s, fu_device_get_name (device);
Version: %s, fu_device_get_version (device);
```

> If the log has to be created during the update, I think this makes sense too:

the `fwupdtool update` stdout/stderr output is already captured into syslog for debugging purpose on the update itself.  I guess we could have a 3rd file descriptor that saves this stuff, but at that point it seems like putting a new argument makes more sense.

**Comment by hughsie** [comment]
> The reason to combine it into the `update` call is to avoid firing off `fwupdtool` multiple times every time a udev supported device is plugged in

How would the log file help that?

**Comment by superm1** [comment]
> How would the log file help that?

`fwupdtool update` launches every time by udev rule and upstart job.  Logging the devices during that launch means the executable runs once to get all devices, save them, and then try to update them.

Of course the alternative can be
```
fwupdtool get-devices > log
fwupdtool update
```

But then that means that `fwupdtool` runs twice every single time even though the information is there the first time.

**Comment by hughsie** [comment]
> But then that means that `fwupdtool` runs twice every single time even though the information is there

We could have some kind of daemon to cache the information, ohh wait, /me grumbles.

> `chrome://system`

So we'd show "the devices that support firmware updates before the last update was done" -- isn't that hugely confusing? It would show stuff that's already been updated as having the wrong version, and would also show devices that have since been disconnected.

I can see the logic to show the current device state in `chrome://system`, but that implies actually querying the daemon from a session process.

I guess one thing we could do is write out a /usr/lib/fwupd/current_state.json which contains all the devices the daemon cares about. It could be updated either at engine start, or after any update action.

I really don't think using fwupd_device_to_string() is a good idea -- somebody will want to "make it pretty" and then it'll be parsed and sadness and breakage will happen. Adding something like `JsonObject *fwupd_device_to_json_object()` would also be useful for another project.

**Comment by superm1** [comment]
> We could have some kind of daemon to cache the information, ohh wait, /me grumbles.

How much easier it would be if the daemon was running to get accurate information.. :stuck_out_tongue_winking_eye: 

> So we'd show "the devices that support firmware updates before the last update was done" -- isn't that hugely confusing? It would show stuff that's already been updated as having the wrong version, and would also show devices that have since been disconnected.

The device prompting this work is supported by dell-dock, which doesn't actually start running the new FW until you call `activate` or unplug it.  So it might be a little disingenuous to log after the update call.

However you're right it might show devices not connected.  It's almost like you would need to run the tool both on the add and remove udev rules to keep it accurate.

> I guess one thing we could do is write out a `/usr/lib/fwupd/current_state.json` which contains all the devices the daemon cares about. It could be updated either at engine start, or after any update action.

I guess `/var/lib/fwupd/current_state.json` you mean.  But this seems reasonable.  I'll rework this.

**Pull request closed without merging**
