### PR TITLE
fu-debug: In non-verbose mode, output colors for errors too

### PR DESCRIPTION
**Pull request by superm1**

### CODE REVIEW

**Comment by superm1** [comment]
And actually I'm tempted to remove the check for `isatty` in the first place.  As I can tell `journalctl` filters the color escape sequences and you can still read logs with tools like `cat` and `grep` to get colored output.    Although opening the logs in a text editor that doesn't support them is not a pretty experience.  Thoughts?

**Comment by hughsie** [comment]
> Although opening the logs in a text editor that doesn't support them is not a pretty experience

I think this would make it much harder for people not familiar with Linux -- I get --verbose outputs in .doc files sometimes and so I think the isatty check needs to stay unfortunately.

What's the logic for outputting colored text in non-verbose mode? Won't that just be dumped to the journal in most cases?

**Comment by superm1** [comment]
> so I think the isatty check needs to stay unfortunately.

Okay

> What's the logic for outputting colored text in non-verbose mode? Won't that just be dumped to the journal in most cases?

Most cases yes - but I'm trying to make the experience with `fwupdtool` better. Right now it's really not obvious what's an error message and so this commit helps distinguish.

**Comment by hughsie** [comment]
> Right now it's really not obvious what's an error message and so this commit helps distinguish.

Couldn't we just wire up `--verbose` and hide the `g_debug`s by default?

**Comment by superm1** [comment]
> Couldn't we just wire up --verbose and hide the g_debugs by default?

That would be unfortunate that `--verbose` means different things on the daemon and the tool.  I at least liked them being the same (and using the same code).

Let me give a more concrete example of my experience.  Running `fwupdtool` it will show something like this:

```
[Loading                      ]Message that is not obviously a warning or error message.
[Decompressing          ]
Installing update on time machine...
[***                              ]
```

With this commit in place that "message that is not obviously a warning or error message" is put in red, so you know there was something wrong.  Additionally you can redirect stderr somewhere and capture errors with this commit then.

**Comment by hughsie** [comment]
> Message that is not obviously a warning or error message

Shouldn't this either be hidden, or be routed through the progressbar to avoid this funky experience?

**Comment by superm1** [comment]
> Shouldn't this either be hidden, or be routed through the progressbar to avoid this funky experience?

Hmm routed through the progress bar - as in `fu_debug` calls into the progressbar somehow on error messages?  Interesting idea.  It would be easier for `fwupdtool`, but might even make sense for `fwupdmgr` too to get daemon warnings in the frontend.

**Comment by hughsie** [comment]
I think if you're using the progressbar you either need to interface with it, or just hide the warnings. If the user can't do anything with the warning (i.e. they can't fix it) I'd probably err on just not showing warnings.

**Comment by superm1** [comment]
OK, I've added another commit to hide that stuff from `fwupdtool` by default.  I would rather keep the colored red messages commit when running on a tty though as I still see it useful when running `/usr/libexec/fwupd` to see colored stuff crop up and to have that be on stderr.

**Comment by hughsie** [comment]
Lets go back a bit -- what's the message you're getting with "Message that is not obviously a warning or error message" -- I'd rather put the hooks in place to use the progress bar correctly, or if the warning really isn't a warning we should demote it as such.

**Comment by superm1** [comment]
> what's the message you're getting with "Message that is not obviously a warning or error message"

It was a warning that was emitted from the plugin that's not yet released.
In this instance (my opinion) is that it really should be warning level.  It was indicating that an device bug was being triggered.

**Comment by hughsie** [comment]
> It was indicating that an device bug was being triggered

That sounds like the thing we need to put API in place for; else it's not going to get shown using gnome-software.

**Comment by superm1** [comment]
> That sounds like the thing we need to put API in place for; else it's not going to get shown using gnome-software.

Well I don't know that I agree - from gnome-software (or fwupdmgr for that matter) seeing that you triggered a device bug isn't going to be useful.  It's mostly warning level so that if you see "impact" from this problem it's been logged somewhere useful that this bug was triggered.

Another way to handle this situation outlined above is to set up fwupdtool stderr output to log somewhere else by default (system journal?).

**Comment by hughsie** [comment]
> It's mostly warning level so that if you see "impact" from this problem 

I'm not sure I follow. The bug is important enough to show in red text, but isn't important enough to show the GUI user? Do you have any other examples of where we might want to show the user this kind of warning/message.

**Comment by superm1** [comment]
The importance is in the eye of the beholder and I think I have a hard time putting a "user" hat on in this instance.

I can think of another instance that we might want to show a message that can be deemed warning.

When you're running a Synaptics MST update if the checksum failed on a bank it retries a number of times.  It might be useful to have a message shown at that time.

**Comment by hughsie** [comment]
> if the checksum failed on a bank it retries a number of times

Is that interesting to the end user? What can they do about the failure? I've tried to avoid scaring the user as much as possible so far, flashing firmware certainly causes anxiety in more than a few people. If it's recoverable, and just for developers -> `g_debug()` IMHO.

**Comment by superm1** [comment]
The only part that is interesting to the user is that the flash process will take more time as a result of the retry.

I guess the same thing if this device bug happens that prompted this set of commits most people don't care about it, it's just logs that it would matter to have it in.

So I "think" the commits as I have them make sense still?
* fwupdtool by default hide all the scary messages
* fwupdmgr/gnome-software if daemon is on a console, show scary messages in red on daemon console (advanced user or debugging).  Don't show anything to fwupdmgr/gnome-software

**Pull request closed without merging**
