### PR TITLE
Avoid clashing with fwupdate (EFI binaries, UEFI boot entry, EFI variables)

### PR DESCRIPTION
**Pull request by superm1**
Since fwup*.efi is now in tree, we want to use that not the one
that comes in fwupdate.

This will handle the transition for debian since there is no signed package in archive yet.  The signed package in Ubuntu will require some extra work.

### CODE REVIEW

**Comment by hughsie** [comment]
I avoided doing this for Fedora as fwupdate can still be installed and used. I'm not completely sure if that's right, as I think the first update you do we're going to nuke the fwupdate-supplied fwup.efi

**Comment by superm1** [comment]
Exactly since fwupd manages the EFI application to make sure it's the one it provides I feel you're not going to have the expected result if you install fwupdate after installing fwupd.

**Comment by superm1** [comment]
So one alternative to keep them coinstallable and cousable is to rename the EFI application that comes with fwupd. Something like "fwupdx64.efi" so that it doesn't clash with fwupdate's "fwupx64.efi".

**Comment by hughsie** [comment]
> So one alternative to keep them coinstallable 

I think this might be best; at least for me I have to test various different combinations for RHEL and it would be a pain to keep downgrading and installing to just switch to the stable branch.

**Comment by superm1** [comment]
Hopefully that catches all the places that we use the name of the EFI application.

**Comment by hughsie** [comment]
Does it work? I guess it should do, but I'm worried the fwup.efi name might be whitelisted somewhere like shim.

**Comment by superm1** [comment]
Untested at the moment. Can't check until Friday.

As I can tell it's not whitelisted anywhere in shim though. The only other place I could see a potential problem is the EFI boot entry name is very similar to fwupdate's so if might not be clear which was which if looking at a POST menu.

**Comment by hughsie** [comment]
I wondered if we could do something better there -- i.e. "Firmware Update" rather than the technical bit.

**Comment by superm1** [comment]
Certainly renaming the string is doable, but due to the mechanism of how shim knows which file to load there will be a \fwupdx64.efi at the end of the boot item.

**Comment by hughsie** [comment]
> there will be a \fwupdx64.efi at the end of the boot item

Yes, I wondered if there was any way around this, e.g. using a `\n` or `\0` to make it look pretty.

**Comment by superm1** [comment]
Here's what it looks like in firmware setup with `\n`.  It does work and do the update and cleanup properly.
(Sorry for the photos taken with a potato).
When you first enter FW setup you see it looking like it hid `\n`.  Once you highlight it it seems to overwrite the below line.

img_20180706_100636665_ll
img_20180706_100645957
img_20180706_100654194

The other thing I realized is that if we're going to be renaming EFI binary and boot entry name to avoid collisions, we need to rename the UEFI variables that are used too.  I'll add that to this PR.

**Comment by superm1** [comment]
`\0` seems to do better.  This works on the Dell system I tried, but I guess I don't know how well it would handle on other systems.  Can you check this on the non-Dell system you were trying?

img_20180706_101631068

**Comment by hughsie** [comment]
I'm glad this works, it certainly looks better. I'll test on Lenovo at the weekend. I think we need to find a crafy way to include the `\0`, atm CI complains with `error: embedded ‘\0’ in format`

**Comment by superm1** [comment]
CI's errors might be true.  I wouldn't be surprised if the embedded `\0` is translating into a memory leak for freeing those strings.  I'll give it some other thought if anything else can be done.

**Comment by superm1** [comment]
You know, I realized that I was testing without secure boot.  Shim isn't in the picture, it was just booting the EFI path encoded DP so of course this is going to work.  A real test means putting shim back in the loop, which fwupd only does when secure boot is on now.

**Comment by superm1** [comment]
I double checked with shim chainloading and it seems to do it just fine without the `\0`, `\n`, or path in the string.  I guess can you please make sure that when you check shim is in the picture too?  I thought shim was reading the "Title" to get the path, but it seems just content to use the end of the DP path too.

```
$ sudo efibootmgr -v
BootNext: 0001
BootCurrent: 0000
Timeout: 0 seconds
BootOrder: 0000,0001
Boot0000* Ubuntu	PciRoot(0x0)/Pci(0x17,0x0)/Sata(2,65535,0)/HD(2,GPT,ec2971a5-8bb3-4108-8b76-895549c8e10a,0x127800,0xfa000)/File(\EFI\ubuntu\shimx64.efi)
Boot0001* Firmware-Updater	HD(2,GPT,ec2971a5-8bb3-4108-8b76-895549c8e10a,0x127800,0xfa000)/File(\EFI\ubuntu\shimx64.efi)\.f.w.u.p.d.x.6.4...e.f.i...
```

**Comment by hughsie** [comment]
This is nontrivial to test on the Fedora builders without an actual tagged build for me. I'll try to grab @vathpela again and ask about the title.

**Comment by superm1** [comment]
Well the way I was testing was)
1. turning on secure boot (to let fwupd think it needs to use the signed file)
2. doing the update
3. On the reboot, turn off secure boot (before it exits POST).
4. Let it run BootNext like normal on next boot.

That does let it work to test the shim chainloading but without needing to do real secure boot.

**Comment by hughsie** [comment]
From Peter: "the issue here is that if we're launched from the EFI shell, for some reason the label is passed as one of the command line arguments"

Apparently it's also the reason there were no spaces allowed in the title too. See https://github.com/rhboot/shim/blob/master/shim.c#L2123

-- although to my perhaps naive eyes I didn't see the title at all in the EFI shell hexdump. Peter provided the original commit for the title https://github.com/rhboot/fwupdate/commit/ed9722394252eed5167dad6c2c12346785f7d61b which shows it was originally a workaround for a long-fixed shim bug.

So, I think we should just make the entry "Linux Firmware Updater" with spaces and no efi path. Maybe rebase your branch and I can test that?

**Comment by superm1** [comment]
Ah, I do recall us hitting this when we were first getting fwupdate working again now in EFI shell.  The EFI shell use case isn't super important anymore (since it reliably executes now), so even if it does still exist I'm not too worried.

Just rebased it.

**Comment by hughsie** [comment]
You need to remove the outdated git commit info:

    1) Add a '\0' in boot entry to try to hide \fwupdx64.efi
   2) Linux-Firmware-Updater to Firmware-Updater

Then LGTM, thanks.

**Pull request merged**
