### PR TITLE
Merge Synaptics MST plugin

### PR DESCRIPTION
**Pull request by superm1**
This plugin introduces support for the Synaptics MST hubs used in Dell systems and docks.
It requires kernel 4.6 or later.

It's been developed in collaboration between Dell and Synaptics.

Once this pull request looks good, I'll squash it down to a few commits.

### CODE REVIEW

**Comment by hughsie** [comment]
I think it looks really good, thanks to you both. If you squash this down to a few commits please merge it to master and then we can run all the usual clang/coverity checks before we cut a new tarball release.

**Comment by superm1** [comment]
OK, i've squashed it down to two commits and will merge.  

Other than clang/coverity checks there are two more things from my perspective i'd like to check before cutting a release:
- Right now the TB16 and WD15 both use the same payload and so we made one GUID for both.  I'm checking if we're confident enough that will stay the same forever.  If not, then need to identify which dock is being used and make a different GUID for different docks.  This is actually a bunch of work to identify which dock is which, and would require a bit of an overhaul of the dell plugin to make a function that does this and is usable by other plugins.
- Although cascading is done and verified with the synaptics-tool, it hasn't yet been verified with the plugin. Since it enumerates devices a little differently, I'd like to make sure we've tested that.

**Comment by hughsie** [comment]
I've committed quite a few fixed to master (including all but one of the coverity issues) but I do still have some reservations if the code is actually going to work correctly. There is some global state in synapticsmst-common.c (ewww) which also includes a file descriptor handle.

What I'd really love to do is fold into the synapticsmst-common code into synapticsmst-device and remove the abstraction, making it clear who owns each property and is responsible for the fd. The abstraction means it's very easy to leak that fd on the error path and it also makes the code very hard to trace, for example synapticsmst_device_disable_remote_control calls synapticsmst_common_config_connection which sets the global state from the device state. The synapticsmst_common_disable_remote_control then calls the config_connection before the action (overwriting the global state) and then after the action (resetting the global state to the parent state). This is pretty nasty.

To actually fix this properly needs some documentation about what "layers" and "rad" actually means. Can someone please add some implementation nodes into the code or README.md file please so we can clean up some of the problems? Thanks.

**Comment by superm1** [comment]
I've asked Pei Chen to share some more information about DP layers and DP rad.  As for the state issues, after getting my test setup with a device that supports cascade I am seeing some problems with the plugin versus what the tool finds with the code dying in enable of remote control.  I haven't completely identified it as caused by this state tracking, but I'll dig into it more later this week.

**Comment by hughsie** [comment]
I've merged 67a756c93f5881025277e313d64ef80577fced63 which I think should work, and might even fix up some bugs with querying cascade devices. There is still some bits I'm not super-happy with (e.g. the `remain_layer` property) but I think the code now should work a bit more reliably. If I've broken things I apologize (I have no hardware to test this), and I'd still very much like some documentation about how all the layers and cascade devices work.

**Comment by superm1** [comment]
Richard, thanks.  I'll test this out with hardware.  
Pei Chen added some comments yesterday while I was out to answer your concerns, but it looks like to the wrong place so you probably didn't see them: https://github.com/dell//fwupd/commit/8a18229

**Comment by hughsie** [comment]
That's useful, thanks. I don't think the code as written supports more than two levels deep devices; it seems the RAD would support devices 8 levels deep -- I don't know how many devices would nest this device but it seems slightly shortsighted to design the plugin for just two levels. A recursive design wouldn't be hard to do, enabling/disabling the remote control as required.

Some questions:

* Is there only 4 ports per layer? What is a "port" -- is it a physical output?
* drm_dp_aux0->3 -- is this some kind of "parent" device? I assume you access the "child" port through the parent drm_dp_aux? Is the kernel exporting up to 4 parents?
* Would it be possible to borrow something like a WD15 for a few weeks?

Richard.

**Comment by superm1** [comment]
Sure.  I'll try to get Pei Chen to comment on this particular thread to answer some of your questions.

**The plugin design** - that was a mistake on my part from interpreting the -tool code when I was bolting  cascade support into the plugin.  The tool does support up to 8 levels deep, but the plugin doesn't currently.

**Levels**
At least in Dell HW, the deepest use of cascade is currently two levels, but I agree it's better to plan for supporting the full amount.  Neither the TB16 or the WD15 use cascasding.  
* The WD15 has a single (direct) MST hub
* The TB16 has dual (direct) MST hubs.  
* Cascading is only currently used in rugged designs (which has made this a little more difficult to validate), but certainly could be used in a future dock or system.

On the **parent/child**
I've seen the kernel export 3 nodes (0->2) on some systems and 2 on others (0->1).  I haven't yet seen one with 4 nodes.  Maybe Synaptics can comment on this.  To access the remote (cascaded) devices uses a remote control feature of their MST hub to pass on data to a remote hub.  I don't believe there is any way to directly address them in this design.  You would need I2C or SMBus for direct addressing (which aren't supported here)

Can you contact me privately and i'll see about sending you something with MST hubs in it.  Let me know what you want to do with it so we can figure out the best thing to send.

**Comment by superm1** [comment]
Oh and on how things are working now - the direct query code still works fine, but cascade querying isn't working still in the plugin.

**Comment by T1323** [comment]
Please refer to the answers below :
1. For current products in Dell (Tesla & Leaf), every layer would have most 2 ports for dp. The "port" in the code means the physical tx port of DP. However, there may have 3 tx dp ports in our new chips so I use 2 bits for a layer.
2. In fact, we don't know how many drm_dp_aux in a system. If it is not always 3 in all system then it would be more robust if we can get the number from graphic driver or kernel.

**Comment by superm1** [comment]
Not sure if github will DTRT to send a notificiation, but in case it does: 
@rantogno and @danvet would you be able to comment on how the kernel decides how many drm_dp_aux devices are created?

The drm_dp_aux kernel driver is being used by Synaptics in a plugin for fwupd to query MST hub firmware versions and flash updated binaries in this driver.  Right now the Synaptics plugin is hardcoding to look for up to 3 (since that's what we've seen in the field), but if  there is a proper interface to query it would be better to change the userspace code to use that.

**Comment by superm1** [comment]
@T1323 Can you review what i've changed in master related to cascade?  I've got the plugin working with cascade now and would like some comments if you think it should be adjusted further (https://github.com/hughsie/fwupd/commit/eebf9f9c7d749851d886a4732e5cd0d0606b514f)

**Comment by T1323** [comment]
@superm1 It looks good to me.

**Comment by superm1** [comment]
@T1323 FYI, I discussed with upstream for the drm-dp-aux kernel module about the number of nodes that will occur.  They said it's based upon the controllers connected, and we shouldn't hardcode.  

These depend on the board you're dealing with, and on the number of
gpus you have in the system (and whether they actually have drivers
loaded for them).

> We should also perhaps expose the aux device node for MST devices. At
> which point the number of aux nodes could change dynamically when you
> plug MST devices in/out.
> 
> So I don't think you should be making any assumptions on the
> number/order of these device nodes.
> 

So I made a change that will look for all devices by iterated sysfs directory: https://github.com/hughsie/fwupd/commit/8c7b98da56df4bcc7059509fa7759f750b0b1891

[1] https://lists.freedesktop.org/archives/intel-gfx/2017-January/117980.html

**Pull request merged**
