### PR TITLE
Fix dbus introspection type of Device signal argument: sa{sv} -> (sa{sv})

### PR DESCRIPTION
**Pull request by tmds**

### CODE REVIEW

**Comment by hughsie** [comment]
I guess that makes sense; they have to be a tuple "on the wire" but all my other projects use the tuple-less type in the introspection file. Out of interest, what makes you think they have to be `(sa{sv})` there?

**Comment by tmds** [comment]
When written as `sa{sv}` this is a sequence of two types: `string` and `dictionary of (string -> variant)`
When written as `(sa{sv})` this is a single type that is a struct that contains the above types.
The dbus spec calls this a _single complete type_.

**Comment by hughsie** [comment]
Right, but I though that all properties in D-Bus were tuples (or single complete type as you said) and therefor the tuple-notation of a signal was inferred?

**Comment by tmds** [comment]
I wish the dbus spec would state more explicit that types in the introspection xml must be single complete.
As a data point. I checked the types used in all the system and session services running on my fedora desktop. This was the only instance where types were not single complete.

**Comment by smcv** [comment]
For completeness: It is also valid, although rare, for an argument to be a tuple itself. If your method or signal has a single argument of type `(si)`, then its D-Bus signature is `"(si)"`. In GDBus, the list of arguments (of length 1) would be represented as a tuple GVariant of length 1 _containing_ the tuple you actually wanted, of type `G_VARIANT_TYPE ("((si))")`.

**Comment by smcv** [comment]
```
-      <arg type='sa{sv}' name='device' direction='out'>
```

This is not valid.

One possible interpretation for what you wanted is that you have one signal argument of type `(sa{sv})`, as in this pull request.

Another possible interpretation is that you have two arguments, `<arg type='s' .../>` and `<arg type='a{sv}' .../>`. This would be the more conventional D-Bus API design.

**Comment by hughsie** [comment]
I think https://github.com/hughsie/fwupd/commit/d424d0d193b5138fc1e131020de7d3447c78e7c2 fixes this, right?

**Comment by tmds** [comment]
> I think d424d0d fixes this, right?

You left out the first string. This matches with what is emitted in the code: https://github.com/hughsie/fwupd/blob/b38a4fdfd631a800d4171a4eb3e519075755f430/src/fu-main.c#L144.
I am not familiar with the API, but I think a change event may want to include the device id: https://github.com/hughsie/fwupd/blob/e76ed8eb0d170f52091e6bab5129d809d2a52972/libfwupd/fwupd-result.c#L1401. Or is this value also in the dictionary: https://github.com/hughsie/fwupd/blob/e76ed8eb0d170f52091e6bab5129d809d2a52972/libfwupd/fwupd-result.c#L1377?

**Comment by tmds** [comment]
@hughsie -^

**Comment by smcv** [comment]
> You left out the first string

After some discussion on IRC it seems that in this case there is no first string: the only signal argument is the `a{sv}` (string => variant dictionary), and all the necessary information (including device ID) is in the dictionary.

The only uses of `sa{sv}` in that code seem to be as dictionary entries, `{sa{sv}}` (note the braces around both single complete types), which are only valid on D-Bus when they appear in an array, `a{sa{sv}}` (which is a dictionary mapping strings to dictionaries).

Or do you have evidence (for instance from `dbus-monitor`) of the type not being `a{sv}`?

**Comment by tmds** [comment]
> all the necessary information (including device ID) is in the dictionary.

This was what I was asking, so good that this is in the dictionary :)

**Pull request closed without merging**
