### PR TITLE
thunderbolt: add description to all FwLocation objects

### PR DESCRIPTION
**Pull request by ybernat**
Completing what discussed in https://github.com/hughsie/fwupd/pull/214

Signed-off-by: Yehezkel Bernat <yehezkel.bernat@intel.com>

### CODE REVIEW

**Comment by ybernat** [comment]
(Some of the lines are maybe too wide now, depends on your taste about it. Please let me know if you want me to reformat them.)

**Comment by gicmo** [comment]
Cool! Like it, but I let @hughsie be the judge of long lines!

**Comment by hughsie** [comment]
Looks fine to me.

**Comment by ybernat** [comment]
> /build/build/PKGBUILD: line 16:   539 Killed                  ninja -v -C ../build
> ==> ERROR: A failure occurred in build().
>     Aborting...

But I don't see why.

**Comment by superm1** [comment]
I've seen that happen a few times on the arch job.  I just kicked it again, it's probably fine.

**Pull request merged**
