### PR TITLE
fu-tool: Show a message during initialization

### PR DESCRIPTION
**Pull request by superm1**
At least in my experience coldplug can take a while (especially when
Thunderbolt is involved).

### CODE REVIEW

**Comment by hughsie** [comment]
I wonder if we can do a little better and provide some more detailed feedback to the user. What about if fu-tool connected to the FuEngine status-changed signal and printf'd that?

**Comment by hughsie** [comment]
> Are you thinking to make status changed more all around useful?

I think so. The FuEngine status is global, i.e. daemon wide and the per-FuDevice status' just get proxied to the global one as a convenience.

> Like show "enumerating device %s" etc?

Well, I don't think it's useful to include which device, just that it's enumerating. Maybe even "LOADING" is enough. I think going from `UNKNOWN` -> `LOADING` -> `IDLE` is probably the thing the client would expect when starting the service.

> composite device updates you don't know what device is being operated on at all while moving through the list.

Well, each device has a status; is that insufficient?

**Comment by superm1** [comment]
OK, I think your idea works fairly well.  You get a "Loading ..." message followed by it being full when done enumerating.  Take a look now.

> Well, each device has a status; is that insufficient?

Well it's more that you run `fwupdmgr/fwupdtool install <blah.cab>` and then you see a progress bar jump between 0 and 100 multiple times with various status messages but don't know what they correspond to.  Almost like you need a message in between processing devices `"Updating %s", fu_device_get_name (device)`

**Comment by hughsie** [comment]
> then you see a progress bar jump between 0 and 100 multiple times with various status messages but don't know what they correspond to.

I suppose you would; I'd not considered this.

> Almost like you need a message in between processing devices "Updating %s"

I'm not sure how you'd achieve this with the current API. Perhaps a better thing to do would be to go 0..100 just once, taking into account the different devices. If it's a composite device then to the user it's "one thing" not "lots of devices". That would obviously needs plumbing, but it's not too hard.

**Comment by superm1** [comment]
Untested, but to give you an idea of along the lines of what I'm thinking.

```
diff --git a/src/fu-engine.c b/src/fu-engine.c
index b54b47a5..532016ff 100644
--- a/src/fu-engine.c
+++ b/src/fu-engine.c
@@ -71,6 +71,7 @@ enum {
 	SIGNAL_DEVICE_CHANGED,
 	SIGNAL_STATUS_CHANGED,
 	SIGNAL_PERCENTAGE_CHANGED,
+	SIGNAL_TRANSACTION_CHANGED,
 	SIGNAL_LAST
 };
 
@@ -90,6 +91,15 @@ fu_engine_emit_device_changed (FuEngine *self, FuDevice *device)
 	g_signal_emit (self, signals[SIGNAL_DEVICE_CHANGED], 0, device);
 }
 
+static void
+fu_engine_emit_transaction_changed (FuEngine *self, const gchar *transaction)
+{
+	/* emit changed */
+	g_debug ("Emitting PropertyChanged('Transaction'='%s')",
+		 transaction);
+	g_signal_emit (self, signals[SIGNAL_TRANSACTION_CHANGED], 0, transaction);
+
+}
 /**
  * fu_engine_get_status:
  * @self: A #FuEngine
@@ -1320,6 +1330,8 @@ fu_engine_install (FuEngine *self,
 		blob_fw2 = g_bytes_ref (blob_fw);
 	}
 
+	fu_engine_emit_transaction_changed (self, fu_device_get_name (device));
+
 	/* install firmware blob */
 	version = as_release_get_version (rel);
 	return fu_engine_install_blob (self, device, blob_cab, blob_fw2,
@@ -3548,6 +3560,12 @@ fu_engine_class_init (FuEngineClass *klass)
 			      G_TYPE_FROM_CLASS (object_class), G_SIGNAL_RUN_LAST,
 			      0, NULL, NULL, g_cclosure_marshal_VOID__UINT,
 			      G_TYPE_NONE, 1, G_TYPE_UINT);
+	signals[SIGNAL_TRANSACTION_CHANGED] =
+		g_signal_new ("transaction-changed",
+			      G_TYPE_FROM_CLASS (object_class), G_SIGNAL_RUN_LAST,
+			      0, NULL, NULL, g_cclosure_marshal_VOID__UINT,
+			      G_TYPE_NONE, 1, G_TYPE_UINT);
+
 }
 
 void
diff --git a/src/fu-tool.c b/src/fu-tool.c
index 0324e9be..e806e38c 100644
--- a/src/fu-tool.c
+++ b/src/fu-tool.c
@@ -281,6 +281,13 @@ fu_main_engine_percentage_changed_cb (FuEngine *engine,
 	fu_progressbar_update (priv->progressbar, FWUPD_STATUS_UNKNOWN, percentage);
 }
 
+static void
+fu_main_engine_transaction_changed_cb (FuEngine *engine,
+				       const gchar *transaction)
+{
+	g_print ("Flashing %s", transaction);
+}
+
 static gboolean
 fu_util_watch (FuUtilPrivate *priv, gchar **values, GError **error)
 {
@@ -874,6 +881,9 @@ main (int argc, char *argv[])
 	g_signal_connect (priv->engine, "percentage-changed",
 			  G_CALLBACK (fu_main_engine_percentage_changed_cb),
 			  priv);
+	g_signal_connect (priv->engine, "transaction-changed",
+			  G_CALLBACK (fu_main_engine_transaction_changed_cb),
+			  priv);
 
 	/* any plugin whitelist specified */
 	for (guint i = 0; plugin_glob != NULL && plugin_glob[i] != NULL; i++)
```

**Comment by hughsie** [comment]
Alternative proposal: https://github.com/hughsie/fwupd/pull/647

**Comment by superm1** [comment]
Thanks that looks good. I think we still need the commit on this PR though (different but related problem with regards to initialization)

**Pull request merged**
