### PR TITLE
installed-tests: Adjust to actually use a remote for installed tests

### PR DESCRIPTION
**Pull request by superm1**
By using a remote, this should allow using gnome-software to do the
installed tests without hacking around much.

### CODE REVIEW

**Comment by superm1** [comment]
I know that I need to sort out `fwupd-tests.conf` getting shoved into packages, but want to make sure CI and you like this otherwise.

**Comment by hughsie** [comment]
In general, like it. I think we need some kind of document explaining how to use the new QA tests no?

**Comment by superm1** [comment]
Sure. Where should it be documented?

The other question is whether this source should be turned on by default or not.

**Comment by hughsie** [comment]
That looks perfect, and basically how I would have done it. Squash and merge if you're happy.

**Pull request merged**
