### PR TITLE
Wip/hughsie/no archive size max

### PR DESCRIPTION
**Pull request by hughsie**

### CODE REVIEW

**Comment by hughsie** [comment]
@jtojnar can you test this branch please.

**Comment by jtojnar** [comment]
```
machine: must succeed: fwupdmgr install /nix/store/8snh14j7wyjhxbfj2w2a1pmhkrln45hz-fwupd-1.0.4-installedTests/share/installed-tests/fwupd/fakedevice124.cab
machine# [    8.937146] do_trap: 123 callbacks suppressed
machine# [    8.937688] traps: .fwupd-wrapped[747] trap int3 ip:7fcba2811a61 sp:7ffd98645d10 error:0
machine# [    8.938568]  in libglib-2.0.so.0.5400.3[7fcba27c2000+112000]
machine# [    8.734779] .fwupd-wrapped[747]: gmem.c:100: failed to allocate 536870912 bytes
```

And after increasing the memory size i get:

```
machine: must succeed: fwupdmgr install /nix/store/8snh14j7wyjhxbfj2w2a1pmhkrln45hz-fwupd-1.0.4-installedTests/share/installed-tests/fwupd/fakedevice124.cab
machine: exit status 1
machine: output: Decompressing…         [***************************************]
Firmware is not for any attached hardware: got b585990a-003e-5270-89d5-3705a17f9a43
```

**Comment by hughsie** [comment]
> failed to allocate 536870912 bytes

The container isn't set up for overcommit?

**Comment by hughsie** [comment]
@superm1 build failure seems to be:

    /usr/lib/gcc/x86_64-linux-gnu/7/../../../x86_64-linux-gnu/libfwup.so: undefined reference to `efi_guid_ux_capsule@LIBEFIVAR_1.32'

**Comment by jtojnar** [comment]
Okay, can confirm this patch fixes the error. Now the problem is the network access requirement.

```
machine: must succeed: echo 'Downgrading to older release (requires network access)'
machine: exit status 0
machine: must succeed: fwupdmgr --verbose downgrade
machine: exit status 1
machine: output: Downloading 1.2.3 for Integrated Webcam™...
(fwupdmgr:877): Fu-DEBUG: creating path /root/.cache/fwupdmgr
(fwupdmgr:877): Fwupd-DEBUG: looking for os-release at /etc/os-release
(fwupdmgr:877): Fu-DEBUG: downloading https://secure-lvfs.rhcloud.com/downloads/cab283ab711036a4180b2b7579b53fc5742993ef-fakedevice123.cab to /root/.cache/fwupdmgr/cab283ab711036a4180b2b7579b53fc5742993ef-fakedb
Fetching firmware https://secure-lvfs.rhcloud.com/downloads/cab283ab711036a4180b2b7579b53fc5742993ef-fakedevice123.cab

Failed to download https://secure-lvfs.rhcloud.com/downloads/cab283ab711036a4180b2b7579b53fc5742993ef-fakedevice123.cab: Cannot resolve hostname
```

**Comment by superm1** [comment]
@hughsie regarding build failure, on it.  It's because of that symbol map being wrong in the efivar release and the symbol being patched in manually (see https://github.com/rhboot/efivar/commit/765f03f9e7956ec39a807c6f1410d8d9c200f7d5)

A no change rebuild of fwupdate will resolve it.
https://bugs.launchpad.net/ubuntu/+source/fwupdate-signed/+bug/1749471

**Pull request merged**
