### PR TITLE
WIP: Publish docs to fwupd.github.io using CircelCI

### PR DESCRIPTION
**Pull request by superm1**
For now this is happening on every master build, but in the future
after it's working reliably it should be restricted to only tagged
builds.

Type of pull request:
- [ ] New plugin (Please include [new plugin checklist](https://github.com/hughsie/fwupd/wiki/New-plugin-checklist))
- [ ] Code fix
- [ ] Feature
- [ ] Documentation

### CODE REVIEW

**Comment by superm1** [comment]
Hopefully i've connected all the dots properly.  If this works out well I was thinking it might make sense to do a move hughsie/fwupd -> fwupd/fwupd and also all fwupd related projects under the same umbrella organization.

It seems to work well for other projects like systemd and home-assistant, but I don't think it will be a requirement for publishing to https://fwupd.github.io

**Comment by superm1** [comment]
None of the CircleCI builds appear to actually create docs.  Maybe i'll have to move one from Travis.

**Comment by hughsie** [comment]
Maybe we should use GitHub actions for this? I'm okay with creating a fwupd organisation, but wonder what other projects it would contain. lvfs-website?

**Comment by superm1** [comment]
>Maybe we should use GitHub actions for this? I'm okay with creating a fwupd organisation, but wonder what other projects it would contain. lvfs-website?

Another CI agent? 🤕 
I nearly got everything in place for CircleCI publishing, I actually had one job get as far as trying to publish last night with the correct SSH key loaded, but wrong directory structure.  Hopefully it's close.

> I'm okay with creating a fwupd organisation, but wonder what other projects it would contain. lvfs-website?

Cool, well I think the logistics for doing it should wait until you're actually back in the office because you have to hit various move buttons to transfer ownership to an organization and setup github redirects properly.

Stuff that I would think:
* fwupd
* solokeys-lvfs
* 8bitdo-firmware
* synaptics-prometheus-firmware
* fwdash
* wacom-firmware
* nitrokey-firmware
* flashrom fork
* realtek-firmware
* aiaiai-firmware
* fwupd-test-firmware
* atusb-firmware
* jabra-firmware
* blinkinlabs-firmware
* hydrabus-firmware
* mirror of gnome-firmware-updater w/ all issues and pull requests turned off (with a mention that it's a mirror to gitlab)
* lvfs-website

**Comment by hughsie** [comment]
I guess all those make sense. Do you think the organisation should be "fwupd" or "lvfs" in that case?

**Comment by superm1** [comment]
> I guess all those make sense. Do you think the organisation should be "fwupd" or "lvfs" in that case?

I was thinking "fwupd", but mostly to get the fwupd.github.io page working.  If it was lvfs then it would be lvfs.github.io.  
Maybe lvfs-website should go to https://github.com/linuxfoundation instead if you don't think it fits?

**Comment by hughsie** [comment]
I think you're right, the LVFS service might split off more from "me" as time goes on (e.g. the people managing the instances might want commit to deploy new versions) so maybe fwupd makes sense indeed.

**Comment by hughsie** [comment]
Ahh, you've already created the org! Can you add me to it please.

**Comment by superm1** [comment]
> Ahh, you've already created the org! Can you add me to it please.

Sure, added.
If you start to migrate stuff, do everything except fwupd.  There are various CI bits that need to be copied over or recorded somehow I think.

Transfer process is here: https://help.github.com/en/articles/transferring-a-repository

**Comment by superm1** [comment]
> Ahh, you've already created the org! Can you add me to it please.

It might make sense to try to move https://github.com/rhboot/fwupdate over there too and mark it deprecated harder.  I guess @vathpela would need to make you an owner of it to let that work though.

**Comment by superm1** [comment]
OK I had my first successful end to end deployment to fwupd.github.io.  I've adjusted it so that it will only run that part of the job when releases are tagged.  You can transfer hughsie/fwupd to fwupd/fwupd now and I'll make sure the rest of the CI stuff with Travis and Circle gets sorted with the move (you might need to do LGTM - I don't know how that works).

**Comment by hughsie** [comment]
Okay, I'll transfer the repo now. Fingers crossed, thanks!

**Pull request merged**
