### PR TITLE
Report the DeviceInstanceIDs to `fwupdmgr get-updates`

### PR DESCRIPTION
**Pull request by hughsie**
This makes it much easier to write metainfo files as we don't have to ask OEMs
or ODMs to run fwupdtool or fwupd with --verbose and then sort through hundreds
of debugging statements.

The fwupdmgr get-devices output also now prints output like this:

    20EQS64N0C System Firmware
      DeviceId:             2c1302f31806a0e0d57c377d99e18dae56351413
      InstanceId:           UEFI\RES_{DDC0EE61-E7F0-4E7D-ACC5-C070A398838E}
      Guid:                 ddc0ee61-e7f0-4e7d-acc5-c070a398838e
      Guid:                 230c8b18-8d9b-53ec-838b-6cfc0383493a

We're deliberately not showing the InstanceId lines in the get-updates command
as the instance IDs are not useful in this case.

Type of pull request:
- [ ] New plugin (Please include [new plugin checklist](https://github.com/hughsie/fwupd/wiki/New-plugin-checklist))
- [ ] Code fix
- [ ] Feature
- [ ] Documentation

### CODE REVIEW

**Comment by superm1** [comment]
At least with cases of multiple GUIDs for the device I have heard confusion of "which do I use"? Which does mean going through --verbose output to map it out.

I think really what we want is a dedicated way to show that information with this too.

**Comment by superm1** [comment]
As a thought maybe "InstanceID (GUID)"?

I do think that this may need to be a restricted access information though like how serial numbers are. It is entirely possible for a GUID to be built using private information about the device that shouldn't generally be available to non root users.

**Comment by hughsie** [comment]
> I think really what we want is a dedicated way to show that information with this too.

Agree. I'll have another go at this.

> It is entirely possible for a GUID to be built using private information about the device

I'd not considered this, and it is a valid concern. I agree treating it like a serial number is best.

**Comment by hughsie** [comment]
What about:

    THNSN5512GPU7 TOSHIBA
      DeviceId:             c82980cd3fe66f7d0a8bb83b353cbc271177efd4
      Guid:                 e22c4520-43dc-5bb3-8245-5787fead9b63 <- NVME\VEN_1179&DEV_010F&REV_01
      Guid:                 83991323-9951-5adf-b743-d93e882a41e1 <- NVME\VEN_1179&DEV_010F
      Guid:                 ad9fe8f7-cdc4-52c9-9fea-31b6f4988ffa <- NVME\VEN_1179

(as root)

**Comment by superm1** [comment]
I think that's perfect

**Comment by hughsie** [comment]
Okay, branch rebased; I think exporting the GUID stuff is perfectly reasonable given it's essentially LVFS API at this point.

**Comment by hughsie** [comment]
I've removed the namespace from `fwupd_guid_from_data()` and replaced it with some flags to choose the namespace. I think it needs to be exported to avoid the daemon having to build a private-internal-only copy of libfwupd -- i'd much rather it just use the system shared lib.

I've also converted all of the plugins to use the new `fu_device_add_instance_id()` -- I agree it's much better being explicit. I deliberately didn't add a warning for the conversion of the GUID as we use `fu_device_add_guid()` and `Guid=` in the quirk file handling and that seems too much like ABI/API.

**Comment by superm1** [comment]
Also, maybe it's worth doing the same thing to nvme too (it makes an implicit dependency on kernel 4.4+ for building though; so that's gotta be considered).

Other than that sort out the clang unused variable from CI and it LGTM.

**Pull request merged**
