### PR TITLE
wacom-usb: Remove the DTH generation hardware as it will not work wit…

### PR DESCRIPTION
**Pull request by hughsie**
…h fwupd

Fixes https://github.com/hughsie/fwupd/issues/882

### CODE REVIEW

**Comment by superm1** [comment]
From looking at that issue I was wondering if it made more sense to analyze hid descriptor rather than the hardcoded list to better scale.

**Comment by hughsie** [comment]
Is there any easy was to parse the HID descriptor? We're not using hidraw, we're using raw GUsbDevice's, so I assume it's in the g_usb_interface_get_extra() data -- but then something needs to parse the blob.

**Comment by superm1** [comment]
I believe you're correct and yes something would need to parse the blob.

**Comment by superm1** [comment]
If that's a bunch of work that's not worth it (IE newer tablets will always have this and those are just older ones) then I think this PR is a fine solution though.

**Comment by hughsie** [comment]
> If that's a bunch of work that's not worth it

It is certainly a rabbit-hole... it's an untrusted binary format, so fuzzing etc is needed too.

**Comment by superm1** [comment]
Right..  I think i'd lean on just remove the ones from the quirk file.  Everything is quirked for that plugin for now.  It's only when you try to start matching on a wildcard for a vendor ID that you need to do this deeper inspection.

**Pull request merged**
