### PR TITLE
trivial: Update LINGUAS

### PR DESCRIPTION
**Pull request by piotrdrag**
Add Asturian, Finnish, and Chinese (Traditional).

### CODE REVIEW

**Comment by hughsie** [comment]
Gahh, sorry. Is there any kind of travis/git hook we can put in place so this kind of thing doesn't happen anymore?

**Comment by piotrdrag** [comment]
I don’t know. :(

**Comment by superm1** [comment]
Could you maybe just have something simple that looks for `.po `files in `po/` and checks that they're in `LINGUAS`?  If that's all it is simple shell script I think can test for that.

**Comment by superm1** [comment]
something like this perhaps?

```
#!/bin/sh
set -e

err=0
for lang in $(ls po/*.po | sed 's,.po,,; s,po/,,;');
do
        if ! grep $lang po/LINGUAS >/dev/null; then
                echo "missing $lang"
                err=1
        fi
done
exit $err
```

**Comment by ebassi** [comment]
You can call that script as part of the test suite.

**Comment by hughsie** [comment]
Agreed; @superm1 can you wire that into the test target in `po` please?

**Comment by superm1** [comment]
I tried to wire it into the test target but struggled with LINGUAS not existing anywhere but the source directory.  So I instead wired into the same place that normally translation deps are looked for.
https://github.com/hughsie/fwupd/commit/268d180e3b494df99dfa87b60873abcc5c5c77cc

**Pull request merged**
