### PR TITLE
Generate a pile of images for status messages during system firmware update.

### PR DESCRIPTION
**Pull request by vathpela**
This generates a pile of .bmp files to use as our status messages.

Signed-off-by: Peter Jones <pjones@redhat.com>

### CODE REVIEW

**Comment by superm1** [comment]
We recently turned on Travis CI and the build failed, with what looks like missing new dependencies (at least cairo so far).  
So these changes should be needed still:
1. In meson.build add a dependency check for the missing stuff
2. In the DockerFiles (`contrib/ci/DockerFile-*`) add the packages for the missing stuff

**Licensing**
* I notice you had a header in the shell script for license under GPL3.  Would you mind adjusting that to GPL2?  The rest of the project is GPL2.
* Can you add a GPL2 header to the python script as well?

**Comment by hughsie** [comment]
Also, didn't we want this in a subpackage? I.e. we need to change contribute/fwupd.spec.in

**Comment by vathpela** [comment]
Alright, will fix up.  Thanks!

**Comment by superm1** [comment]
Thanks for sorting that.  Can you adjust the licensing too?

**Comment by vathpela** [comment]
I think the current version (71759bf) addresses everything mentioned above.

**Comment by vathpela** [comment]
... but don't merge it just yet.  There's a math error and all the images are too large.

**Comment by vathpela** [comment]
Okay, fixed in fb546b2, feel free to merge.

**Pull request merged**
