### PR TITLE
ata: send ATA standby immediate when activating firmware

### PR DESCRIPTION
**Pull request by superm1**
This should flush all remaining writes and make the drive safe to
update.

I don't have the ability to actually test this though.

Type of pull request:
- [ ] New plugin (Please include [new plugin checklist](https://github.com/hughsie/fwupd/wiki/New-plugin-checklist))
- [ ] Code fix
- [x] Feature
- [ ] Documentation

### CODE REVIEW

**Comment by hughsie** [comment]
Although I can't see any functional difference, it did succeed:

    10:28:35:0084 FuPlugin             performing activate() on ata
    10:28:35:0084 FuPluginAta          CBD:            a1 0a 20 00 00 00 00 00 e0 e0 00 00 
    10:28:35:0103 FuPluginAta          ATA_12 status=0x2, host_status=0x0, driver_status=0x8
    10:28:35:0103 FuPluginAta          SB:             70 00 05 00 00 00 00 0a 00 50 e0 03 21 04 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 
    10:28:35:0103 FuPluginAta          ATA_12 stat=00 err=03 nsect=04 lbal=00 lbam=00 lbah=00 dev=00
    10:28:35:0103 FuPluginAta          CBD:            a1 0a 20 0f 04 00 00 00 00 92 00 00 
    10:28:35:0120 FuPluginAta          ATA_12 status=0x2, host_status=0x0, driver_status=0x8
    10:28:35:0120 FuPluginAta          SB:             70 00 05 00 00 00 00 0a 00 50 a0 02 21 04 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 
    10:28:35:0120 FuPluginAta          ATA_12 stat=00 err=02 nsect=04 lbal=00 lbam=00 lbah=00 dev=00

**Comment by superm1** [comment]
Can you capture dmesg on the drive you checked while the activate command runs?

I got some binaries for the drive I'm trying and I'm noticing this.

```
[   19.044060] ata1.00: exception Emask 0x0 SAct 0x0 SErr 0x0 action 0x0
[   19.044065] ata1.00: failed command: STANDBY IMMEDIATE
[   19.044072] ata1.00: cmd e0/00:00:00:00:00/00:00:00:00:00/e0 tag 16
                        res 50/00:00:00:00:00/00:00:00:00:00/a0 Emask 0x40 (internal error)
[   19.044075] ata1.00: status: { DRDY }
[   19.047415] ata1.00: configured for UDMA/133
[   19.047424] ata1: EH complete
[   19.047460] ata1.00: Enabling discard_zeroes_data
[   19.077107] ata1.00: exception Emask 0x0 SAct 0x0 SErr 0x0 action 0x0
[   19.077118] ata1.00: failed command: DOWNLOAD MICROCODE
[   19.077134] ata1.00: cmd 92/0f:04:00:00:00/00:00:00:00:00/00 tag 24
                        res 50/00:00:30:08:00/00:00:00:00:00/a0 Emask 0x40 (internal error)
[   19.077142] ata1.00: status: { DRDY }
```

**Comment by hughsie** [comment]
I get literally nothing in `dmesg` or the journal.

**Comment by superm1** [comment]
Hmm.  I'm not sure what's missing/different then for this drive.  Running the same standby immediate command `-y` from hdparm doesn't show the same kernel errors.  The only thing different there that I can tell is that it tries two different standby immediate commands (`ATA_OP_STANDBYNOW1` then `ATA_OP_STANDBYNOW2`), but if that was the difference I would have expected a similar error in the kernel log when it tried to do `ATA_OP_STANDBYNOW1`.

**Comment by superm1** [comment]
Well stracing I can see it's definitely a differently filled ioctl.
```
ioctl(16, SG_IO, {interface_id='S', dxfer_direction=SG_DXFER_TO_DEV, cmd_len=12, cmdp="\xa1\x0a\x20\x00\x00\x00\x00\x00\x40\xe0\x00\x00", mx_sb_len=32, iovec_count=0, dxfer_len=0, timeout=120000, flags=0, dxferp=NULL, status=0x2, masked_status=0x1, msg_status=0, sb_len_wr=18, sbp="\x70\x00\x05\x00\x0
0\x00\x00\x0a\x00\x50\xa0\x00\x21\x04\x00\x00\x00\x00", host_status=0, driver_status=0x8, resid=0, duration=48, info=SG_INFO_CHECK}) = 0
```

hdparm
```
ioctl(3, SG_IO, {interface_id='S', dxfer_direction=SG_DXFER_NONE, cmd_len=16, cmdp="\x85\x06\x20\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x40\xe0\x00", mx_sb_len=32, iovec_count=0, dxfer_len=0, timeout=15000, flags=0, status=0x2, masked_status=0x1, msg_status=0, sb_len_wr=22, sbp="\x72\x01\x00\x1d\x00
\x00\x00\x0e\x09\x0c\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x40\x50", host_status=0, driver_status=0x8, resid=0, duration=28, info=SG_INFO_CHECK}) = 0
```

**Pull request merged**
