### PR TITLE
trivial: Add a write_firmware() vfunc to FuDevice

### PR DESCRIPTION
**Pull request by hughsie**

### CODE REVIEW

**Comment by hughsie** [comment]
This is needed as a prerequisite to https://github.com/hughsie/fwupd/pull/508

**Comment by superm1** [comment]
Don't some of the other plugins need this too?

**Comment by hughsie** [comment]
> Don't some of the other plugins need this too?

I've added one more. A few of the others need a bit of rework, but that shouldn't block this PR until we come to remove their `-tool.c` files :)

**Comment by superm1** [comment]
> I've added one more. A few of the others need a bit of rework, but that shouldn't block this PR until we come to remove their -tool.c files :)

OK :)

**Pull request merged**
