### PR TITLE
Correctly get the check the new version for devices that replug

### PR DESCRIPTION
**Pull request by hughsie**
There are a lot of failures in the LVFS with 'device version not updated on
success' and this is because we were looking at the original FuDevice, rather
than the FuDevice that came back after the bootloader replug phase.

Before doing the check get the new FuDevice to prevent failing the check with
a false positive.

### CODE REVIEW

**Comment by superm1** [comment]
The fix looks fine to me, but I would ask if you can comment more on what the large number of failures are applying to?  Is it ebitdo or something else?

**Comment by hughsie** [comment]
> Is it ebitdo or something else?

Logitech Unifying.

**Comment by hughsie** [comment]
Also, I added a known issue on the LVFS to triage all the 77 affected reports.

**Comment by superm1** [comment]
Great thanks!

**Pull request merged**
