### PR TITLE
libfwupd: Generate a static library

### PR DESCRIPTION
**Pull request by superm1**
This library can be used to create tools that would operate standalone
without a current fwupd installed by linking libfwupd into the tool.

To accomplish this:
1) Rename the static library generated by src/meson.build to match
more closely what it is (s/libfwupdprivate/fwupdprivate/)
2) Create a static library for libfwupd (libfwupdprivate)

### CODE REVIEW

**Comment by hughsie** [comment]
Google actually hinted they wanted something similar. What's the bigger plan here?

**Comment by superm1** [comment]
A few purposes.

1. Early bring up work. Being able to swap payloads on devices without having to repack cabs or know anything about metadata.
`tool write $file $deviceid` is how I'm using initially in my in development plugin.
2. Being able to run said tool in environments with older fwupd installed and not needing to upgrade.

I don't see these tools using this as being packaged and distributed in general purpose distros.

3. It's interesting google was mentioning similar.. I was thinking _Maybe_ building tools that can be dropped in a limited environment like chromeos. They can be easily wrapped and use all plug-in functionality.

**Comment by hughsie** [comment]
We do have a lot of little in-tree-noinst tools which could be removed with this kind of change. Would this imply a new main() program in src/ that can run-intree plugin(s) and the engine? The engine would need tweaks (would we record history?) but I could also see this tool installed in libexec for debugging. We do something similar in packagekit too. If the new tool has to handle composite devices and multiple installs then some of the stuff needs to move from fu-main.c to either the engine or another shared file.

**Comment by superm1** [comment]
My original goal was a very simple application that would load the plugin but I ran into some challenges with that when running `fu_plugin_init` where some symbols wouldn't resolve that were needed by the plugin and normally available when running in the daemon. Rather than fix at the time I concluded that for <1> it's easier to have a single statically linked file and linked all the source files I needed in which resolved the symbols just fine and the tool works properly.

So all that said the way I did it is absolutely generic and I think can be the start of a basis for your idea. 

I'll post the tool part of what I did so far into a 🌲.

**Comment by superm1** [comment]
Here's the generic tool as it stands right now: https://github.com/hughsie/fwupd/commit/b0fe94044ebd5703327d2fd4566c00eb192f626b

I think if we do follow through with your idea for a generic "tree-wide" tool that loads all plugins it's best to align to the same command names as `fwupdmgr` (eg instead of `info` like I used use `get-devices`).

In thinking about a generic tool supporting composite devices I think I'd like to see two different install commands.  One of them `install` that behaves likes `fwupdmgr install` behaves and one that is `write` which behaves similar to my `write`.  My `write` takes the payload as the argument (and optionally the device ID). If you don't provide device ID I prompt for it.

**Comment by superm1** [comment]
So considering comments in https://github.com/hughsie/fwupd/pull/508 can this be merged now and #508 can then be rebased on this?

**Comment by hughsie** [comment]
I'm not sure yet. The "use without installing" thing is going to be trickier than just a static library, given we have quirks, plugins, config files and all that jazz.

**Comment by superm1** [comment]
Superseded by the stuff in https://github.com/hughsie/fwupd/pull/514

**Pull request closed without merging**
