### PR TITLE
Actually make sure our firmware status string will get translated.

### PR DESCRIPTION
**Pull request by vathpela**
Maybe there's a better way to do this; I don't know.

Signed-off-by: Peter Jones <pjones@redhat.com>

### CODE REVIEW

**Comment by hughsie** [comment]
I asked Allan about this a while ago; does ccda0d2be7c06d5a85e91c7bed12655b76c0743d do what you need? It is a different string, but it's the one he wanted.

**Comment by vathpela** [comment]
Yeah, that works (except it means I've got the string wrong in make-images.sh).  I'm a bit concerned about the ellipsis.  How about da6314f ?

**Comment by hughsie** [comment]
Why not the ellipsis? It's in the human interface guidelines as it's a continuing operation.

**Comment by vathpela** [comment]
Oh really?  I think it looks weird, but if it's in the guidelines, I guess that's justification enough.  I note that it's /already/ being translated inconsistently, though, between unicode ellipsis and just a pile of dots.

**Comment by vathpela** [comment]
So I think 16826532e216da5 will do basically what we both want, then?

**Pull request merged**
