### PR TITLE
Allow providers to set an alternate GUID.

### PR DESCRIPTION
**Pull request by superm1**
Alternate GUID's can be used to allow switching devices between different
modes or firmwares than a linear fashion allows.

Flashing an alternate GUID will require the usage of the '--force' flag
introduced previously.

### CODE REVIEW

**Comment by hughsie** [comment]
Although I think this patch would fix the problem, I think we need a slightly more generic solution. Other vendors have been encouraging me to support devices that support more than GUID for usual runtime (rather than switching modes) and I think we might have to bite the bullet and do this larger solution.

**Comment by hughsie** [comment]
(I can look at this today)

**Comment by hughsie** [comment]
I've merged the multi-GUID patch, but thinking about this some more I don't actually think the 2-in-1 device should use this feature... If we add both GUIDs to the single device then I think we we're going to be offering updates to the user for the device in the alternate mode, which we really don't want to do.

My new plan (and what I'm willing to help with) means that we actually create *two* FuDevices for the multi-mode device we talked about, each one with a single GUID. When in the legacy mode the FuDevice will just have FLAG_INTERNAL set, and the other "fake" device will have FLAG_INTERNAL *and* FLAG_DISABLED set. By "org.freedesktop.fwupd.Enable()ing" the fake device we disable the "real" device which means we can then upload new firmware to switch the device mode.

This also means it magically works in GNOME Software and fwupdmgr without any extra work. From an end user point of view they can switch device modes doing:

    fwupdmgr enable whatever:00
    fwupdmgr install foo.cab

... where enable would require the admin password. I've not checked anything in to allow this yes as I'm not quite convinced about the enable/disable wording, it seems a bit non-specific. Other options I thought of were:

 * DISARMED
 * DEACTIVATED
 * HIDDEN

But then we really want the policy prompt to be quite specific about what the action consequences are, so I did want to know what you think the auth message should look like. Something like "Activating this device may alter system operation" perhaps -- without making it too specific to what we're trying to do.

**Comment by superm1** [comment]
On Tue, May 17, 2016 at 3:58 AM Richard Hughes <notifications@github.com>
wrote:

> I've merged the multi-GUID patch, but thinking about this some more I
> don't actually think the 2-in-1 device should use this feature... If we add
> both GUIDs to the single device then I think we we're going to be offering
> updates to the user for the device in the alternate mode, which we really
> don't want to do.
>
Yeah in the way that it's merged I agree.

> My new plan (and what I'm willing to help with) means that we actually
> create *two* FuDevices for the multi-mode device we talked about, each
> one with a single GUID. When in the legacy mode the FuDevice will just have
> FLAG_INTERNAL set, and the other "fake" device will have FLAG_INTERNAL
> *and* FLAG_DISABLED set. By "org.freedesktop.fwupd.Enable()ing" the fake
> device we disable the "real" device which means we can then upload new
> firmware to switch the device mode.
>
OK.  So this makes sense to me, but I worry about what the experience in
gnome-software (or other GUI tools) would look like.  The current policy in
gnome-software doesn't show firmware devices on the system unless there is
something actionable (for example unlock or update).

The last thing I would want is to make it seem like the only option
available was to switch to the other mode (which would be expected to not
be the norm).  Most of the time people shouldn't touch this unless they
know they need to.

Personally i'm fine leaving it behind fwupdmgr command line only and
kicking how to use it to a wiki or documentation.

This also means it magically works in GNOME Software and fwupdmgr without
> any extra work. From an end user point of view they can switch device modes
> doing:
>
> fwupdmgr enable whatever:00
> fwupdmgr install foo.cab
>
> ... where enable would require the admin password. I've not checked
> anything in to allow this yes as I'm not quite convinced about the
> enable/disable wording, it seems a bit non-specific. Other options I
> thought of were:
>
>    - DISARMED
>    - DEACTIVATED
>    - HIDDEN
>
> When I first read your response I thought 'enable' feels too similar to
'unlock' and is likely to confuse people even more what the difference
between enabled and unlocked are.

My favorite (particularly in the situation we're referring to) would be
"HIDDEN".


>
> But then we really want the policy prompt to be quite specific about what
> the action consequences are, so I did want to know what you think the auth
> message should look like. Something like "Activating this device may alter
> system operation" perhaps -- without making it too specific to what we're
> trying to do.
>
What about allowing the provider to provide a specific string about the
consequences?  This does seem like it will be quite specific to each device
that would use a feature like multi-mode.

**Comment by hughsie** [comment]
Right, I don't think we want to offer to switch modes in gnome-software. Like you say, add this in the docs somewhere.

> What about allowing the provider to provide a specific string about the consequences

No can do, the providers can't provide translations, and the polkit auth can't show random strings when you're using gnome-shell. The string is related to what to call the DBus method too; one combination I've just thought of would be:

    MASKED -> Unmask()

Where mask is defined as "conceal something from view". We already have HIDDEN in the libdfu library that basically means "ignore" IIRC. Unmask would have something like "Authentication is required to unmask a system device on this machine" which is suitably scary.

Richard.

**Comment by superm1** [comment]
On Tue, May 17, 2016 at 8:17 AM Richard Hughes <notifications@github.com>
wrote:

> Right, I don't think we want to offer to switch modes in gnome-software.
> Like you say, add this in the docs somewhere.
>
> What about allowing the provider to provide a specific string about the
> consequences
>
> No can do, the providers can't provide translations, and the polkit auth
> can't show random strings when you're using gnome-shell.
>
Oh sorry that wasn't clear.  I meant to allow provider' specific strings
and actions to org.freedesktop.fwupd.policy.in (that maps to generic
unhide, unmask, etc whatever is decided).
So you can have a generic action with a generic string that can be
overridden if the provider desired to be more specific.

> The string is related to what to call the DBus method too; one combination
> I've just thought of would be:
>
> MASKED -> Unmask()
>
> Where mask is defined as "conceal something from view". We already have
> HIDDEN in the libdfu library that basically means "ignore" IIRC. Unmask
> would have something like "Authentication is required to unmask a system
> device on this machine" which is suitably scary.
>
When something was unmasked would you envision that the provider would get
called out to do something while unmasking too?  At least with my situation
I think it would be appropriate that if the device was unmasked that the
currently active device should be masked.  Both shouldn't be available
simultaneously.  You wouldn't to be offering updates for both.

>

**Comment by hughsie** [comment]
> When something was unmasked would you envision that the provider would get
called out to do something while unmasking too?

Yes, and this is what I started doing until I realized I was basically duplicating `fu_provider_unlock()`

Thinking rationally, we have three kinds of devices that are in some way locked

* PCI devices that have OptionROM
* Fake devices so that we can enable the ESRT `UEFI-dummy-dev0`
* Multi-mode devices for the non-active firmware type

We want 1 and 2 to be automatically unlocked when required, and 3 to only be unlocked on the command line. 1 and 2 cannot be updated using fwupd, only 3 can be after unlock. We don't want to show 1 or 3 ever in the `get_updates()` results.

I think we can achieve what we want to do by doing the following:

* Only set the `ALLOW_OFFLINE` flag for the unlocked device and not the locked fake device
* Only add devices to the `GetUpdates` result set if either `ALLOW_OFFLINE` or `ALLOW_ONLINE` is set, i.e. the update is able to be applied
* When device `foo` is unlocked, make sure that the device `bar` is looses the `ALLOW_OFFLINE` flag -- which means the provider has to keep track of the "alternate" device (e.g. we add something like `fu_device_set_alternate_device()`) and the unlocked device sets the `ALLOW_OFFLINE` flag

Does that sound sane?

**Comment by superm1** [comment]
Yeah that sounds sane to me.  I think the alternate device setting helper
function would be better than needing to keep track of an iterable hash
table of devices in the provider and how they're related.

It does mean some extra checks would need to be put in the unlock method of
the provider similar to safety checks we discussed in updates too.  If
those safety checks fail, the unlock and switch over would fail too.

**Comment by hughsie** [comment]
>Yeah that sounds sane to me.

Okay, I've pushed some some that to master. Okay to close this PR?

**Comment by superm1** [comment]
Yeah that looks good.  I'll rebase my stuff on that and test out the flow,
go ahead on close this PR.

**Pull request closed without merging**
