### PR TITLE
Additions to ru.po

### PR DESCRIPTION
**Pull request by Ashark**
Added some translations and fixed incorrect translation

### CODE REVIEW

**Comment by hughsie** [comment]
Hey! Thanks for doing those; all our translations go through transifex at https://www.transifex.com/freedesktop/fwupd/ and get synced at release time -- could you submit them there please?

**Comment by Ashark** [comment]
I have created account at transifex.com, but for some reason it is impossible to join Russian translation team, although Russian is listed in list of project's languages. I have done a language request.

**Comment by hughsie** [comment]
Many thanks, I'm sure Misha or Yuri will approve you soon. If it's more than a week then please remind me and I'll poke them myself.

**Comment by superm1** [comment]
@Ashark did you end up getting into transifex?  I believe we should close this PR since the strings won't come in this way, but if you didn't get in maybe @hughsie will need to poke someone.

**Pull request closed without merging**
