### PR TITLE
Return the authority and timestamp as part of the signing validation

### PR DESCRIPTION
**Pull request by hughsie**
This means we return an error when encountering a rollback attack. This can
currently be performed by providing the old metadata and old signature when
calling into UpdateMetadata.

### CODE REVIEW

**Comment by superm1** [comment]
This certainly helps the given problem.  It's not perfect though because all someone would need to do is empty the cache and they can use older metadata/sig again.  

I know you can make the argument you need root to empty the cache but depending on whether packaging clears the state directory on uninstall that might be a simple as uninstalling fwupd through gnome-software and reinstalling.

The only real way you'll be able to guarantee is if you can have a third party attestation source (like a TPM) to store the last timestamp.

**Comment by hughsie** [comment]
> I know you can make the argument you need root to empty the cache 

I was... :)

> but depending on whether packaging clears the state directory on uninstall that might be a simple as uninstalling fwupd through gnome-software and reinstalling.

I don't think fwupd should be visible or uninstallable in gnome-software.

> The only real way you'll be able to guarantee is if you can have a third party attestation source (like a TPM) to store the last timestamp.

Right, although I think this is slightly out of scope for this kind of thing. I'm really trying to solve the "mirror out of date" issue more than the malicious user hellbent on destroying the system. At least from a UEFI point of view you'd hope that any security or incompatible NVRAM change has the "lowest downgrade version" raised in the new BIOS.

One thing I wasn't sure of was allowing the "authority" to change -- It shouldn't unless something unusual happens, but I don't want to paint ourselves into a corner if the LVFS moves my openshift to the Linux Foundation, for example. Maybe just a journal warning?

**Comment by superm1** [comment]
> I don't think fwupd should be visible or uninstallable in gnome-software.

Ah right, it's not shipping .desktop files, shouldn't be exposed.

> Right, although I think this is slightly out of scope for this kind of thing. I'm really trying to solve the "mirror out of date" issue more than the malicious user hellbent on destroying the system. At least from a UEFI point of view you'd hope that any security or incompatible NVRAM change has the "lowest downgrade version" raised in the new BIOS.

Right.

> One thing I wasn't sure of was allowing the "authority" to change -- It shouldn't unless something unusual happens, but I don't want to paint ourselves into a corner if the LVFS moves my openshift to the Linux Foundation, for example. Maybe just a journal warning?

If LVFS moves, would it be a light switch HTTP redirect?  I would expect a new remote source to be created for the move, maybe some temporary mirroring in place and patching distros to introduce the new remote for pulling the new place.

**Comment by hughsie** [comment]
> If LVFS moves, would it be a light switch HTTP redirect?

I don't think so; I think it makes sense to do a 2nd instance (with a different GPG key) -- with one mirroring the other for a few months -- then if the one at LF works, I'll just switch things over to be a redirect.

Richard.

**Pull request merged**
