### PR TITLE
Use help2man to generate the man page at build time

### PR DESCRIPTION
**Pull request by hughsie**
The man pages are always old and out-of-sync with the actual tool, so just
generate them using the output of --help.

Fixes https://github.com/hughsie/fwupd/issues/285

### CODE REVIEW

**Comment by superm1** [comment]
Can you add dependency to `debian/control `too?

**Comment by hughsie** [comment]
Not easily, as contrib is beng processed after src. What would it do anyway?

**Comment by superm1** [comment]
I mean literally in the debian control file, not processing that directory (still can't automatically generate debian/control, but i have some ideas)

**Comment by hughsie** [comment]
Ohh, sorry! I thought you meant a meson dependency. Of course, will add.

**Comment by hughsie** [comment]
the other thing, is if we want to convert dfu-tool.1 to using this same method, which lets us drop docbook2man and a ton of SGMLy stuff. The downside is the verbose text might not go very well into the C file...

**Pull request merged**
