### PR TITLE
Drop some data from to_string and json methods that shouldn't export in text frontends

### PR DESCRIPTION
**Pull request by superm1**
Type of pull request:
- [ ] New plugin (Please include [new plugin checklist](https://github.com/hughsie/fwupd/wiki/New-plugin-checklist))
- [x] Code fix
- [ ] Feature
- [ ] Documentation

### CODE REVIEW

**Comment by hughsie** [comment]
I think we need that data, I just don't think fwupdmgr should use to_string. We certainly need to translate each header for example.

**Comment by hughsie** [comment]
Yes, the more I think about this the less we want to use _to_string() with anything we show the user. My proposal would be a `fu_util_device_to_string()` and `fu_util_release_to_string()` in `src/fu-util-common.c` with each field translated, which can be used from either tool. We already have some of the translations in `fu_util_get_updates()` and it's only my lazyness that's stopped me doing something generic before.

That also lets us add the `name` as a proper "field" in `fwupd-device.c` rather than using it as a title which makes the other `to_string()`-using code look weird.

If you want to have a crack at this I'd be glad, otherwise say and I'll find some time next week.

**Comment by superm1** [comment]
I've pushed something that takes a stab at doing that.  I've intentionally dropped a ton of fields that I don't think are useful to people.  Example:

```
BC501 NVMe SK hynix 128GB
  DeviceId:             f954c7acdf5fab61aeaca1cd71d29ea5ade6992f
  Guid:                 b637d847-48b0-519f-a4f1-ed2b8535d300 <- STORAGE-DELL-107442
  Guid:                 da85e71f-d425-e811-b467-0ed5f89f718b
  Serial:               FI83Q060610103M66
  Summary:              NVM Express Solid State Drive
  Flags:                internal|updatable|require-ac|registered|needs-reboot|no-auto-instance-ids
  Vendor:               SK hynix
  VendorId:             NVME:0x1C5C
  Version:              80001C0T
  VersionFormat:        plain
  Created:              2019-08-18

BC501 NVMe SK hynix 128GB
  Identification:	f954c7acdf5fab61aeaca1cd71d29ea5ade6992f
  Summary:		NVM Express Solid State Drive
  Version:		80001C0T
  Vendor:		SK hynix (NVME:0x1C5C)
  Serial number:	FI83Q060610103M66
  Flags:		internal|updatable|require-ac|registered|needs-reboot|no-auto-instance-ids
```

So here are my questions/comments:
* Do you agree to generally stop showing the dropped fields?
* Maybe we should leave `fwupdtool` using the `to_string` methods so that the data is still _easily_ accessible for debugging purposes
* Another option is to call `to_string` methods when the client is run with verbose (it is indeed a lot more verbose information..)
* What do you want to do with all the padding functions?  It seems unfortunate to duplicate them.  Another thought here is to move all this into another new library function for a simpler string view (IE `fwupd_device_to_simple_string`), but of course translations aren't really an option then.

Feel free to modify the branch in any way you see fit, this was just 20 minutes to illustrate problem areas and discuss.

**Comment by hughsie** [comment]
I've pushed a fixup, I think it's looking good now. I can't test properly as my hardware is at home, but feel free to fix up and rebase.

**Comment by superm1** [comment]
I tested and adjusted two things:
1. Fixed the install duration string showing up
2. Prevented the device being printed twice in `--verbose`

I'm still not convinced on leaving GUIDs in there though.  What will most people do with that info?

Also, it's unfortunate that with this change we'll lose the instance ID printing with administrative rights (eg `Guid:                 b637d847-48b0-519f-a4f1-ed2b8535d300 <- STORAGE-DELL-107442`)
But I guess people can just run `sudo fwupdmgr get-devices --verbose` to get that.

**Pull request merged**
