### PR TITLE
Add support for installing against multiple devices in CAB

### PR DESCRIPTION
**Pull request by superm1**
This matches all devices that are in the CAB and runs install on them.

Since the matching of the devices was moved later on, the trust and downgrade checks need to be ran differently.

This was the thought process I applied to the logic:

- If install isn't able to run on any one device, the reason why is recorded in error and output with g_debug (some devices might not ever be installable)
- If install wasn't able to run on any device, the reason for the failure on the last device is returned along with a failure.
- If install is able to run on a device, but the provider fails on that device, the whole method will return failure.
- If Install runs successfully on all devices, return success.

By going about it that way, all installable devices need to return success for a TRUE return.   If a device isn't installable, don't fail unless all aren't installable.

### CODE REVIEW

**Comment by hughsie** [comment]
I've pushed a set of patches derived from your patches (thanks!) to master, but I've tackled things in slightly a different way. Some comments:

 * Pushing all the prototypes to a .h file isn't required and doesn't match any of the existing style, sorry
 * I think it is useful to install a specific firmware to a single device (rather than all at once, only), so I've dropped the last two commits. The default for `install` is "*" so I think that's fine.
 * I did all the sanity checks first, aborting all updates if any failed.
 * I'm aborting the provider update as soon as one fails, I didn't like the delayed GError thing at all - is that really required?

Can you test master and see if it works with your mult-device cab? I'm happy to make changes as required, but I think my patches are somewhat safer with regard to races around the authentication step and somewhat less invasive.

**Comment by superm1** [comment]
On Wed, Jun 29, 2016 at 5:18 AM Richard Hughes <notifications@github.com>
wrote:

> I've pushed a set of patches derived from your patches (thanks!) to
> master, but I've tackled things in slightly a different way. Some comments:
>

>    - Pushing all the prototypes to a .h file isn't required and doesn't
>    match any of the existing style, sorry
>
> The reason I had done this was just to avoid having to reshuffle the order
of fu-main.h in a commit or arbitrarily add more prototypes to the top of
fu-main.c, it seemed like a cleaner approach.

>
>    - I think it is useful to install a specific firmware to a single
>    device (rather than all at once, only), so I've dropped the last two
>    commits. The default for install is "*" so I think that's fine.
>
> OK.  Not a big deal, didn't realize that was still something you wanted to
intentionally keep.

>
>    - I did all the sanity checks first, aborting all updates if any
>    failed.
>
>
>    - I'm aborting the provider update as soon as one fails, I didn't like
>    the delayed GError thing at all - is that really required?
>
> Can you test master and see if it works with your mult-device cab? I'm
> happy to make changes as required, but I think my patches are somewhat
> safer with regard to races around the authentication step and somewhat less
> invasive.
>
I should have mentioned in my comments that I originally had this approach
too, but ran into deficiencies.  Not all updates are always strictly
increasing versions, or strictly are always updatable.

I updated the dell-support branch to merge in your new stuff, but it's not
functional with a real world scenario.
In my example scenario only one component have changed, but others keep the
same version from that payload.

Since you abort immediately on an already installed version for one
component, it doesn't even try on the others.  The approach I had basically
had iterated over some errors like this that are deemed failure in your
implementation and only tried to install on the ones it could.

$ fwupdmgr install ./dock_changed_package.cab --verbose
 * Decompressing firmware
Specified firmware is already installed '0.1.1.8'

$ fwupdmgr get-devices
Dell WD15 Port Controller 1
  Guid:                 8ba2b709-6f97-47fc-b7e7-6a87b578fe25
  DeviceID:             DELL-8ba2b709-6f97-47fc-b7e7-6a87b578fe25lu
  Provider:             Dell
  Flags:                allow-offline|require-ac
  Version:              0.1.1.8
  Created:              2016-06-29
  UpdateVersion:        0.1.1.8
  Trusted:              none

Dell WD15 MST Hub
  Guid:                 7bee2a28-b909-540d-9fa9-6a4c9611d992
  DeviceID:             DELL-7bee2a28-b909-540d-9fa9-6a4c9611d992lu
  Provider:             Dell
  Flags:                require-ac
  Created:              2016-06-29

Dell WD15
  Guid:                 e7ca1f36-bf73-4574-afe6-a4ccacabf479
  DeviceID:             DELL-e7ca1f36-bf73-4574-afe6-a4ccacabf479lu
  Provider:             Dell
  Flags:                allow-offline|require-ac
  Version:              0.0.0.67
  Created:              2016-06-29

$ fwupdmgr get-details ./dock_changed_package.cab (snipped for relevant
pieces)
Dock Package Version Update
  Guid:                 e7ca1f36-bf73-4574-afe6-a4ccacabf479
  DeviceID:             DELL-e7ca1f36-bf73-4574-afe6-a4ccacabf479lu
  Description:          <p>Updating the system firmware improves
performance.</p>
  Flags:                allow-offline|require-ac
  AppstreamId:          com.dell.uefie7ca1f36.firmware
  Summary:              Firmware for the Dell Dock Package Version
  UpdateVersion:        0.0.0.68
  FilenameCab:          firmware.bin
  License:              proprietary
  Size:                 2.0 MB
  UrlHomepage:          http://support.dell.com/
  Vendor:               Dell Inc.
  Trusted:              none
Dell WD15 TI v1.1.8 Port Controller 1 Update
  Guid:                 8ba2b709-6f97-47fc-b7e7-6a87b578fe25
  DeviceID:             DELL-8ba2b709-6f97-47fc-b7e7-6a87b578fe25lu
  Description:          <p>Updating the system firmware improves
performance.</p>
  Flags:                allow-offline|require-ac
  AppstreamId:          com.dell.uefi8ba2b709.firmware
  Summary:              Firmware for the Dell Dell WD15 TI v1.1.8 Port
Controller 1
  UpdateVersion:        0.1.1.8
  FilenameCab:          firmware.bin
  License:              proprietary
  Size:                 2.0 MB
  UrlHomepage:          http://support.dell.com/
  Vendor:               Dell Inc.
  Trusted:              none
Dell Dock MST Hub Update
  Guid:                 7bee2a28-b909-540d-9fa9-6a4c9611d992
  DeviceID:             DELL-7bee2a28-b909-540d-9fa9-6a4c9611d992lu
  Description:          <p>Updating the system firmware improves
performance.</p>
  Flags:                require-ac
  AppstreamId:          com.dell.uefi7bee2a28.firmware
  Summary:              Firmware for the Dell Dell Dock MST Hub
  UpdateVersion:        0.0.0
  FilenameCab:          dock_mst.bin
  License:              proprietary
  UrlHomepage:          http://support.dell.com/
  Vendor:               Dell Inc.
  Trusted:              none

**Comment by hughsie** [comment]
On 29 June 2016 at 15:54, Mario Limonciello <notifications@github.com> wrote:
> I should have mentioned in my comments that I originally had this approach
> too, but ran into deficiencies. Not all updates are always strictly
> increasing versions, or strictly are always updatable.

Ohh hmm, I didn't think of this, sorry. So we need to support the case
of doing something like this:

local:
device A=1.0.0
device B=2.0.0
device C=3.0.0

cab, with:
B=2.1.1
C=3.0.0

Richard.

**Comment by superm1** [comment]
Yep exactly.

**Comment by superm1** [comment]
The other thing in there is that some devices might not be marked as updateable (allow-offline or allow-online missing in flags).  Those shouldn't cause the whole CAB to error out if an update for them is present in the CAB but can't yet be run by any provider.

That's the case for MST hub and NVM.  An update will be distributed in the CAB for them, but implementing an update method for them in the provider is a separate effort that will require extra kernel work and interfaces that aren't yet ready.

**Comment by superm1** [comment]
I --force pushed this change request to rebase on what you've done.

I've added a change above that makes those failures non-critical so that the whole package can be processed.  See what you think of that?

Also, are you sure you're still not crazy about delayed GError?  The eventual error message really can't be useful (as in my commit above) unless you've cached them as you moved along the stuff in the archive.

In the most common case of one file in an archive a delayed GError would get the right message across at least.

**Comment by hughsie** [comment]
I've pushed a set of commits that break up your patch and do it slightly differently. The GPtrArray's actually have two different types (FuDevice v.s. FuDeviceItem) so I think your patch would have exploded specifying a device manually. Can you check master for sanity please :) I also added the delayed GError thing, you were right that we'd just show an unhelpful error in the common case.

**Comment by superm1** [comment]
Yes, this looks good now, thanks.

**Pull request closed without merging**
